<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<meta charset="utf-8">
<meta name="generator" content="quarto-1.5.57">
<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">
<title>3&nbsp; Zhijun H – Stock Market Volatility: Patterns and Predictions</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { display: inline-block; text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>

<script src="../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../site_libs/quarto-search/fuse.min.js"></script>
<script src="../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../">
<link href="../src/appx/effective teamwork - Zhijun.html" rel="next">
<link href="../src/EDA - Phoebe Pan.html" rel="prev">
<script src="../site_libs/cookie-consent/cookie-consent.js"></script>
<link href="../site_libs/cookie-consent/cookie-consent.css" rel="stylesheet">
<script src="../site_libs/quarto-html/quarto.js"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../site_libs/quarto-html/anchor.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" class="quarto-color-scheme" id="quarto-text-highlighting-styles">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-dark.css" rel="prefetch" class="quarto-color-scheme quarto-color-alternate" id="quarto-text-highlighting-styles">
<script src="../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" class="quarto-color-scheme" id="quarto-bootstrap" data-mode="light">
<link href="../site_libs/bootstrap/bootstrap-dark.min.css" rel="prefetch" class="quarto-color-scheme quarto-color-alternate" id="quarto-bootstrap" data-mode="dark"><script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script><script type="text/javascript" charset="UTF-8">
document.addEventListener('DOMContentLoaded', function () {
cookieconsent.run({
  "notice_banner_type":"simple",
  "consent_type":"implied",
  "palette":"light",
  "language":"en",
  "page_load_consent_levels":["strictly-necessary","functionality","tracking","targeting"],
  "notice_banner_reject_button_hide":false,
  "preferences_center_close_button_hide":false,
  "website_name":""
  ,
"language":"en"
  });
});
</script><style>html{ scroll-behavior: smooth; }</style>
<script src="../site_libs/kePrint-0.0.1/kePrint.js"></script><link href="../site_libs/lightable-0.0.1/lightable.css" rel="stylesheet">
<link rel="stylesheet" href="../style/custom.css">
</head>
<body class="nav-sidebar docked">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top"><nav class="quarto-secondary-nav"><div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="../src/EDA - Phoebe Pan.html">EDA</a></li><li class="breadcrumb-item"><a href="../src/EDA - Zhijun He.html"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Zhijun H</span></a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Search" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav></header><!-- content --><div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-full">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation docked overflow-auto"><div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="../">Starfall</a> 
        <div class="sidebar-tools-main">
  <a href="" class="quarto-color-scheme-toggle quarto-navigation-tool  px-1" onclick="window.quartoToggleColorScheme(); return false;" title="Toggle dark mode"><i class="bi"></i></a>
  <a href="" class="quarto-reader-toggle quarto-navigation-tool px-1" onclick="window.quartoToggleReader(); return false;" title="Toggle reader mode">
  <div class="quarto-reader-toggle-btn">
  <i class="bi"></i>
  </div>
</a>
</div>
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Report</span></span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true">
 <span class="menu-text">EDA</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 show">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../src/EDA - Phoebe Pan.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Phoebe P</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../src/EDA - Zhijun He.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Zhijun H</span></span></a>
  </div>
</li>
      </ul>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="true">
 <span class="menu-text">Teamwork</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-2" class="collapse list-unstyled sidebar-section depth1 show">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../src/appx/effective teamwork - Zhijun.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Zhijun H</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../src/appx/effective teamwork - Phoebe.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Phoebe P</span></span></a>
  </div>
</li>
      </ul>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" role="navigation" aria-expanded="true">
 <span class="menu-text">Appendices</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-3" class="collapse list-unstyled sidebar-section depth1 show">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../src/appx/proposal.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Proposal</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../src/appx/case-study.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Case Study</span></span></a>
  </div>
</li>
      </ul>
</li>
    </ul>
</div>
</nav><div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active"><h2 id="toc-title">Table of contents</h2>
   
  <ul>
<li><a href="#data-import-and-preparation" id="toc-data-import-and-preparation" class="nav-link active" data-scroll-target="#data-import-and-preparation"><span class="header-section-number">3.1</span> Data Import and Preparation</a></li>
  <li><a href="#data-structure-and-quality-assessment" id="toc-data-structure-and-quality-assessment" class="nav-link" data-scroll-target="#data-structure-and-quality-assessment"><span class="header-section-number">3.2</span> Data Structure and Quality Assessment</a></li>
  <li><a href="#price-trends-and-market-evolution" id="toc-price-trends-and-market-evolution" class="nav-link" data-scroll-target="#price-trends-and-market-evolution"><span class="header-section-number">3.3</span> Price Trends and Market Evolution</a></li>
  <li><a href="#volatility-analysis-the-heartbeat-of-markets" id="toc-volatility-analysis-the-heartbeat-of-markets" class="nav-link" data-scroll-target="#volatility-analysis-the-heartbeat-of-markets"><span class="header-section-number">3.4</span> Volatility Analysis: The Heartbeat of Markets</a></li>
  <li><a href="#market-correlations-the-global-financial-web" id="toc-market-correlations-the-global-financial-web" class="nav-link" data-scroll-target="#market-correlations-the-global-financial-web"><span class="header-section-number">3.5</span> Market Correlations: The Global Financial Web</a></li>
  <li><a href="#temporal-patterns-cycles-and-seasonality" id="toc-temporal-patterns-cycles-and-seasonality" class="nav-link" data-scroll-target="#temporal-patterns-cycles-and-seasonality"><span class="header-section-number">3.6</span> Temporal Patterns: Cycles and Seasonality</a></li>
  <li><a href="#advanced-volatility-analysis-risk-regimes" id="toc-advanced-volatility-analysis-risk-regimes" class="nav-link" data-scroll-target="#advanced-volatility-analysis-risk-regimes"><span class="header-section-number">3.7</span> Advanced Volatility Analysis: Risk Regimes</a></li>
  <li><a href="#summary-statistics-and-performance-metrics" id="toc-summary-statistics-and-performance-metrics" class="nav-link" data-scroll-target="#summary-statistics-and-performance-metrics"><span class="header-section-number">3.8</span> Summary Statistics and Performance Metrics</a></li>
  <li><a href="#insights-and-conclusions" id="toc-insights-and-conclusions" class="nav-link" data-scroll-target="#insights-and-conclusions"><span class="header-section-number">3.9</span> Insights and Conclusions</a></li>
  </ul></nav>
    </div>
<!-- main -->
<main class="content column-body" id="quarto-document-content"><header id="title-block-header" class="quarto-title-block default"><nav class="quarto-page-breadcrumbs quarto-title-breadcrumbs d-none d-lg-block" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="../src/EDA - Phoebe Pan.html">EDA</a></li><li class="breadcrumb-item"><a href="../src/EDA - Zhijun He.html"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Zhijun H</span></a></li></ol></nav><div class="quarto-title">
<div class="quarto-title-block"><div><h1 class="title">
<span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Zhijun H</span>
</h1><button type="button" class="btn code-tools-button dropdown-toggle" id="quarto-code-tools-menu" data-bs-toggle="dropdown" aria-expanded="false"><i class="bi"></i> Code</button><ul class="dropdown-menu dropdown-menu-end" aria-labelelledby="quarto-code-tools-menu"><li><a id="quarto-show-all-code" class="dropdown-item" href="javascript:void(0)" role="button">Show All Code</a></li><li><a id="quarto-hide-all-code" class="dropdown-item" href="javascript:void(0)" role="button">Hide All Code</a></li><li><hr class="dropdown-divider"></li><li><a id="quarto-view-source" class="dropdown-item" href="javascript:void(0)" role="button">View Source</a></li></ul></div></div>
</div>



<div class="quarto-title-meta column-body">

    
  
    
  </div>
  


</header><section id="data-import-and-preparation" class="level2" data-number="3.1"><h2 data-number="3.1" class="anchored" data-anchor-id="data-import-and-preparation">
<span class="header-section-number">3.1</span> Data Import and Preparation</h2>
<p>In this analysis, I’m examining the historical performance and volatility patterns of six major global stock indices across different market cycles. The selection of indices provides a balanced geographic representation covering North America, Europe, and Asia, allowing for comprehensive cross-market comparison.</p>
<div class="cell">
<details class="code-fold"><summary>Code</summary><div class="sourceCode cell-code" id="cb1"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1"></a><span class="co"># Load required packages</span></span>
<span id="cb1-2"><a href="#cb1-2"></a><span class="fu">library</span>(tidyverse)</span>
<span id="cb1-3"><a href="#cb1-3"></a><span class="fu">library</span>(tidyquant)</span>
<span id="cb1-4"><a href="#cb1-4"></a><span class="fu">library</span>(lubridate)</span>
<span id="cb1-5"><a href="#cb1-5"></a><span class="fu">library</span>(TTR)</span>
<span id="cb1-6"><a href="#cb1-6"></a><span class="fu">library</span>(zoo)</span>
<span id="cb1-7"><a href="#cb1-7"></a><span class="fu">library</span>(gtsummary)</span>
<span id="cb1-8"><a href="#cb1-8"></a><span class="fu">library</span>(janitor)</span>
<span id="cb1-9"><a href="#cb1-9"></a><span class="fu">library</span>(visdat)</span>
<span id="cb1-10"><a href="#cb1-10"></a></span>
<span id="cb1-11"><a href="#cb1-11"></a><span class="co"># Define global market indices</span></span>
<span id="cb1-12"><a href="#cb1-12"></a>indices <span class="ot">&lt;-</span> <span class="fu">c</span>(</span>
<span id="cb1-13"><a href="#cb1-13"></a>  <span class="st">"^GSPC"</span> <span class="ot">=</span> <span class="st">"S&amp;P 500"</span>,      <span class="co"># USA</span></span>
<span id="cb1-14"><a href="#cb1-14"></a>  <span class="st">"^FTSE"</span> <span class="ot">=</span> <span class="st">"FTSE 100"</span>,     <span class="co"># UK  </span></span>
<span id="cb1-15"><a href="#cb1-15"></a>  <span class="st">"^N225"</span> <span class="ot">=</span> <span class="st">"Nikkei 225"</span>,   <span class="co"># Japan</span></span>
<span id="cb1-16"><a href="#cb1-16"></a>  <span class="st">"^GDAXI"</span> <span class="ot">=</span> <span class="st">"DAX"</span>,         <span class="co"># Germany</span></span>
<span id="cb1-17"><a href="#cb1-17"></a>  <span class="st">"^FCHI"</span> <span class="ot">=</span> <span class="st">"CAC 40"</span>,       <span class="co"># France</span></span>
<span id="cb1-18"><a href="#cb1-18"></a>  <span class="st">"^HSI"</span> <span class="ot">=</span> <span class="st">"Hang Seng"</span>      <span class="co"># Hong Kong</span></span>
<span id="cb1-19"><a href="#cb1-19"></a>)</span>
<span id="cb1-20"><a href="#cb1-20"></a></span>
<span id="cb1-21"><a href="#cb1-21"></a><span class="co"># Import historical market data</span></span>
<span id="cb1-22"><a href="#cb1-22"></a>market_data <span class="ot">&lt;-</span> <span class="fu">tq_get</span>(</span>
<span id="cb1-23"><a href="#cb1-23"></a>  <span class="fu">names</span>(indices),</span>
<span id="cb1-24"><a href="#cb1-24"></a>  <span class="at">get =</span> <span class="st">"stock.prices"</span>,</span>
<span id="cb1-25"><a href="#cb1-25"></a>  <span class="at">from =</span> <span class="st">"2000-01-01"</span>,</span>
<span id="cb1-26"><a href="#cb1-26"></a>  <span class="at">to =</span> <span class="fu">Sys.Date</span>()</span>
<span id="cb1-27"><a href="#cb1-27"></a>) <span class="sc">%&gt;%</span></span>
<span id="cb1-28"><a href="#cb1-28"></a>  <span class="co"># Add descriptive names for better readability</span></span>
<span id="cb1-29"><a href="#cb1-29"></a>  <span class="fu">mutate</span>(<span class="at">index_name =</span> indices[symbol])</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
<div style="margin: 20px 0; padding: 15px; border-radius: 5px; background-color: #f8f9fa; border: 1px solid #dee2e6;">
<h3 style="margin-top: 0; color: #495057;" class="anchored">
Data Import Summary
</h3>
<table style="width: 100%; border-collapse: collapse;">
<tbody><tr>
<td style="padding: 8px; font-weight: bold; width: 30%;">
Dataset Size:
</td>
<td style="padding: 8px;">
38,474 observations
</td>
</tr>
<tr>
<td style="padding: 8px; font-weight: bold; border-top: 1px solid #dee2e6;">
Time Period:
</td>
<td style="padding: 8px; border-top: 1px solid #dee2e6;">
Jan 03, 2000 to May 09, 2025
</td>
</tr>
<tr>
<td style="padding: 8px; font-weight: bold; border-top: 1px solid #dee2e6;">
Market Coverage:
</td>
<td style="padding: 8px; border-top: 1px solid #dee2e6;">
6 global indices
</td>
</tr>
</tbody></table>
<h4 style="margin-top: 20px; color: #495057;" class="anchored">
Geographic Distribution
</h4>
<table style="width: 100%; border-collapse: collapse; margin-bottom: 10px;">
<tbody><tr>
<th style="text-align: left; padding: 8px; background-color: #e9ecef; width: 30%;">
Region
</th>
<th style="text-align: left; padding: 8px; background-color: #e9ecef;">
Indices
</th>
</tr>
<tr>
<td style="padding: 8px; font-weight: bold;">
North America
</td>
<td style="padding: 8px;">
S&amp;P 500 (United States)
</td>
</tr>
<tr>
<td style="padding: 8px; font-weight: bold; background-color: #f2f2f2;">
Europe
</td>
<td style="padding: 8px; background-color: #f2f2f2;">
FTSE 100 (UK), DAX (Germany), CAC 40 (France)
</td>
</tr>
<tr>
<td style="padding: 8px; font-weight: bold;">
Asia
</td>
<td style="padding: 8px;">
Nikkei 225 (Japan), Hang Seng (Hong Kong)
</td>
</tr>
</tbody></table>
</div>
<p>The data collection process leverages the tidyquant package’s integration with Yahoo Finance to retrieve daily trading information for each index from January 2000 through May 2025. This extensive timeframe encompasses multiple economic cycles, bull and bear markets, and several major financial crises, providing a robust foundation for volatility analysis. For each index, I capture standard OHLC (Open, High, Low, Close) price data along with trading volume and adjusted prices that account for dividends and splits.</p>
</section><section id="data-structure-and-quality-assessment" class="level2" data-number="3.2"><h2 data-number="3.2" class="anchored" data-anchor-id="data-structure-and-quality-assessment">
<span class="header-section-number">3.2</span> Data Structure and Quality Assessment</h2>
<div class="dataset-overview" style="background-color: #f8f9fa; padding: 15px; border-radius: 5px; margin-bottom: 20px; border-left: 5px solid #4682B4;">
<h3 style="margin-top: 0;" class="anchored">
Dataset Overview
</h3>
<table style="width: auto; margin-bottom: 15px;">
<tbody><tr>
<td style="padding-right: 20px; font-weight: bold;">
Observations:
</td>
<td>
38,474
</td>
</tr>
<tr>
<td style="padding-right: 20px; font-weight: bold;">
Date Range:
</td>
<td>
January 03, 2000 to May 09, 2025
</td>
</tr>
<tr>
<td style="padding-right: 20px; font-weight: bold;">
Market Indices:
</td>
<td>
6
</td>
</tr>
</tbody></table>
</div>
<div class="cell">
<details class="code-fold"><summary>Code</summary><div class="sourceCode cell-code" id="cb2"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1"></a><span class="co"># Create more informative missing values visualization with improved styling</span></span>
<span id="cb2-2"><a href="#cb2-2"></a><span class="fu">vis_miss</span>(market_data) <span class="sc">+</span></span>
<span id="cb2-3"><a href="#cb2-3"></a>  <span class="fu">labs</span>(</span>
<span id="cb2-4"><a href="#cb2-4"></a>    <span class="at">title =</span> <span class="st">"Missing Values Distribution in Market Dataset"</span>,</span>
<span id="cb2-5"><a href="#cb2-5"></a>    <span class="at">subtitle =</span> <span class="st">"White areas represent available data, black indicates missing values"</span>,</span>
<span id="cb2-6"><a href="#cb2-6"></a>    <span class="at">caption =</span> <span class="st">"Source: Yahoo Finance data retrieved via tidyquant package, Analysis by Zhijun H, May 2025"</span></span>
<span id="cb2-7"><a href="#cb2-7"></a>  ) <span class="sc">+</span></span>
<span id="cb2-8"><a href="#cb2-8"></a>  <span class="fu">theme_minimal</span>() <span class="sc">+</span></span>
<span id="cb2-9"><a href="#cb2-9"></a>  <span class="fu">theme</span>(</span>
<span id="cb2-10"><a href="#cb2-10"></a>    <span class="at">plot.title =</span> <span class="fu">element_text</span>(<span class="at">face =</span> <span class="st">"bold"</span>, <span class="at">size =</span> <span class="dv">14</span>),</span>
<span id="cb2-11"><a href="#cb2-11"></a>    <span class="at">plot.subtitle =</span> <span class="fu">element_text</span>(<span class="at">size =</span> <span class="dv">11</span>, <span class="at">color =</span> <span class="st">"gray30"</span>),</span>
<span id="cb2-12"><a href="#cb2-12"></a>    <span class="at">axis.text.x =</span> <span class="fu">element_text</span>(<span class="at">angle =</span> <span class="dv">45</span>, <span class="at">hjust =</span> <span class="dv">1</span>),</span>
<span id="cb2-13"><a href="#cb2-13"></a>    <span class="at">plot.caption =</span> <span class="fu">element_text</span>(<span class="at">color =</span> <span class="st">"gray50"</span>, <span class="at">size =</span> <span class="dv">9</span>),</span>
<span id="cb2-14"><a href="#cb2-14"></a>    <span class="at">panel.grid.minor =</span> <span class="fu">element_blank</span>()</span>
<span id="cb2-15"><a href="#cb2-15"></a>  )</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details><div class="cell-output-display">
<div>
<figure class="figure"><p><img src="EDA---Zhijun-He_files/figure-html/missing_values_viz-1.png" class="img-fluid figure-img" width="864"></p>
</figure>
</div>
</div>
</div>
<div class="cell">
<details class="code-fold"><summary>Code</summary><div class="sourceCode cell-code" id="cb3"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1"></a><span class="co"># Create visually enhanced completeness chart</span></span>
<span id="cb3-2"><a href="#cb3-2"></a><span class="fu">ggplot</span>(completeness_by_index, </span>
<span id="cb3-3"><a href="#cb3-3"></a>       <span class="fu">aes</span>(<span class="at">x =</span> <span class="fu">reorder</span>(index_name, completeness_percent), <span class="at">y =</span> completeness_percent, <span class="at">fill =</span> index_name)) <span class="sc">+</span></span>
<span id="cb3-4"><a href="#cb3-4"></a>  <span class="fu">geom_col</span>(<span class="at">width =</span> <span class="fl">0.7</span>, <span class="at">alpha =</span> <span class="fl">0.9</span>) <span class="sc">+</span></span>
<span id="cb3-5"><a href="#cb3-5"></a>  <span class="fu">geom_text</span>(</span>
<span id="cb3-6"><a href="#cb3-6"></a>    <span class="fu">aes</span>(<span class="at">label =</span> <span class="fu">paste0</span>(completeness_percent, <span class="st">"%"</span>)),</span>
<span id="cb3-7"><a href="#cb3-7"></a>    <span class="at">vjust =</span> <span class="sc">-</span><span class="fl">0.5</span>, </span>
<span id="cb3-8"><a href="#cb3-8"></a>    <span class="at">color =</span> <span class="st">"gray30"</span>, </span>
<span id="cb3-9"><a href="#cb3-9"></a>    <span class="at">size =</span> <span class="fl">3.8</span>,</span>
<span id="cb3-10"><a href="#cb3-10"></a>    <span class="at">fontface =</span> <span class="st">"bold"</span></span>
<span id="cb3-11"><a href="#cb3-11"></a>  ) <span class="sc">+</span></span>
<span id="cb3-12"><a href="#cb3-12"></a>  <span class="fu">labs</span>(</span>
<span id="cb3-13"><a href="#cb3-13"></a>    <span class="at">title =</span> <span class="st">"Data Completeness by Global Market Index"</span>,</span>
<span id="cb3-14"><a href="#cb3-14"></a>    <span class="at">subtitle =</span> <span class="st">"Percentage of calendar days with available trading data from 2000-2025"</span>,</span>
<span id="cb3-15"><a href="#cb3-15"></a>    <span class="at">x =</span> <span class="cn">NULL</span>,</span>
<span id="cb3-16"><a href="#cb3-16"></a>    <span class="at">y =</span> <span class="st">"Completeness (%)"</span>,</span>
<span id="cb3-17"><a href="#cb3-17"></a>    <span class="at">caption =</span> <span class="st">"Source: Yahoo Finance data retrieved via tidyquant package, Analysis by Zhijun H, May 2025"</span></span>
<span id="cb3-18"><a href="#cb3-18"></a>  ) <span class="sc">+</span></span>
<span id="cb3-19"><a href="#cb3-19"></a>  <span class="fu">scale_y_continuous</span>(</span>
<span id="cb3-20"><a href="#cb3-20"></a>    <span class="at">limits =</span> <span class="fu">c</span>(<span class="dv">0</span>, <span class="dv">100</span>),</span>
<span id="cb3-21"><a href="#cb3-21"></a>    <span class="at">breaks =</span> <span class="fu">seq</span>(<span class="dv">0</span>, <span class="dv">100</span>, <span class="at">by =</span> <span class="dv">20</span>),</span>
<span id="cb3-22"><a href="#cb3-22"></a>    <span class="at">labels =</span> <span class="cf">function</span>(x) <span class="fu">paste0</span>(x, <span class="st">"%"</span>)</span>
<span id="cb3-23"><a href="#cb3-23"></a>  ) <span class="sc">+</span></span>
<span id="cb3-24"><a href="#cb3-24"></a>  <span class="fu">scale_fill_brewer</span>(<span class="at">palette =</span> <span class="st">"Set2"</span>) <span class="sc">+</span></span>
<span id="cb3-25"><a href="#cb3-25"></a>  <span class="fu">theme_minimal</span>() <span class="sc">+</span></span>
<span id="cb3-26"><a href="#cb3-26"></a>  <span class="fu">theme</span>(</span>
<span id="cb3-27"><a href="#cb3-27"></a>    <span class="at">legend.position =</span> <span class="st">"none"</span>,</span>
<span id="cb3-28"><a href="#cb3-28"></a>    <span class="at">plot.title =</span> <span class="fu">element_text</span>(<span class="at">face =</span> <span class="st">"bold"</span>, <span class="at">size =</span> <span class="dv">14</span>),</span>
<span id="cb3-29"><a href="#cb3-29"></a>    <span class="at">plot.subtitle =</span> <span class="fu">element_text</span>(<span class="at">size =</span> <span class="dv">11</span>, <span class="at">color =</span> <span class="st">"gray30"</span>),</span>
<span id="cb3-30"><a href="#cb3-30"></a>    <span class="at">axis.text.x =</span> <span class="fu">element_text</span>(<span class="at">angle =</span> <span class="dv">45</span>, <span class="at">hjust =</span> <span class="dv">1</span>, <span class="at">face =</span> <span class="st">"bold"</span>),</span>
<span id="cb3-31"><a href="#cb3-31"></a>    <span class="at">axis.text.y =</span> <span class="fu">element_text</span>(<span class="at">face =</span> <span class="st">"bold"</span>),</span>
<span id="cb3-32"><a href="#cb3-32"></a>    <span class="at">plot.caption =</span> <span class="fu">element_text</span>(<span class="at">color =</span> <span class="st">"gray50"</span>, <span class="at">size =</span> <span class="dv">9</span>),</span>
<span id="cb3-33"><a href="#cb3-33"></a>    <span class="at">panel.grid.minor =</span> <span class="fu">element_blank</span>()</span>
<span id="cb3-34"><a href="#cb3-34"></a>  )</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details><div class="cell-output-display">
<div>
<figure class="figure"><p><img src="EDA---Zhijun-He_files/figure-html/completeness_chart-1.png" class="img-fluid figure-img" width="864"></p>
</figure>
</div>
</div>
</div>
<div class="cell">
<div class="cell-output-display">
<table class="table table-striped table-hover table-condensed caption-top table-sm small" data-quarto-postprocess="true">
<caption>Data Completeness Metrics by Index</caption>
<thead><tr class="header">
<th data-quarto-table-cell-role="th" style="text-align: left; font-weight: bold; background-color: rgba(245, 245, 245, 255) !important;">Index</th>
<th data-quarto-table-cell-role="th" style="text-align: center; font-weight: bold; background-color: rgba(245, 245, 245, 255) !important;">Start Date</th>
<th data-quarto-table-cell-role="th" style="text-align: center; font-weight: bold; background-color: rgba(245, 245, 245, 255) !important;">End Date</th>
<th data-quarto-table-cell-role="th" style="text-align: right; font-weight: bold; background-color: rgba(245, 245, 245, 255) !important;">Trading Days</th>
<th data-quarto-table-cell-role="th" style="text-align: center; font-weight: bold; background-color: rgba(245, 245, 245, 255) !important;">Completeness (%)</th>
</tr></thead>
<tbody>
<tr class="odd">
<td style="text-align: left; font-weight: bold;">CAC 40</td>
<td style="text-align: center;">Jan 03, 2000</td>
<td style="text-align: center;">May 08, 2025</td>
<td style="text-align: right;">6,514</td>
<td style="text-align: center; font-weight: bold; color: white !important; background-color: rgba(40, 167, 69, 255) !important;">70.4</td>
</tr>
<tr class="even">
<td style="text-align: left; font-weight: bold;">DAX</td>
<td style="text-align: center;">Jan 03, 2000</td>
<td style="text-align: center;">May 08, 2025</td>
<td style="text-align: right;">6,479</td>
<td style="text-align: center; font-weight: bold; color: white !important; background-color: rgba(40, 167, 69, 255) !important;">70.0</td>
</tr>
<tr class="odd">
<td style="text-align: left; font-weight: bold;">FTSE 100</td>
<td style="text-align: center;">Jan 04, 2000</td>
<td style="text-align: center;">May 08, 2025</td>
<td style="text-align: right;">6,452</td>
<td style="text-align: center; font-weight: bold; color: white !important; background-color: rgba(255, 193, 7, 255) !important;">69.7</td>
</tr>
<tr class="even">
<td style="text-align: left; font-weight: bold;">Hang Seng</td>
<td style="text-align: center;">Jan 03, 2000</td>
<td style="text-align: center;">May 08, 2025</td>
<td style="text-align: right;">6,322</td>
<td style="text-align: center; font-weight: bold; color: white !important; background-color: rgba(255, 193, 7, 255) !important;">68.3</td>
</tr>
<tr class="odd">
<td style="text-align: left; font-weight: bold;">Nikkei 225</td>
<td style="text-align: center;">Jan 04, 2000</td>
<td style="text-align: center;">May 09, 2025</td>
<td style="text-align: right;">6,331</td>
<td style="text-align: center; font-weight: bold; color: white !important; background-color: rgba(255, 193, 7, 255) !important;">68.4</td>
</tr>
<tr class="even">
<td style="text-align: left; font-weight: bold;">S&amp;P 500</td>
<td style="text-align: center;">Jan 03, 2000</td>
<td style="text-align: center;">May 08, 2025</td>
<td style="text-align: right;">6,376</td>
<td style="text-align: center; font-weight: bold; color: white !important; background-color: rgba(255, 193, 7, 255) !important;">68.9</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>The dataset consists of nearly 38,500 daily observations across six major global indices spanning over 25 years. The completeness analysis reveals consistent data availability across all markets, with completeness ratios between 68-70%. This pattern aligns with expectations given that trading doesn’t occur on weekends and holidays, which typically account for approximately 30% of calendar days annually.</p>
<p>European indices (FTSE 100, DAX, and CAC 40) show slightly higher completeness rates, potentially reflecting fewer market holidays compared to Asian exchanges. The Hang Seng index exhibits the lowest completeness at 68.3%, which can be attributed to extended New Year celebrations and additional regional holidays observed in Hong Kong. These small variations in data availability don’t significantly impact our analysis, as each index still provides robust coverage across the entire study period.</p>
<p>This thorough assessment confirms we have a high-quality dataset with consistent trading information across different market environments, providing a solid foundation for examining volatility patterns through multiple economic cycles and global events.</p>
</section><section id="price-trends-and-market-evolution" class="level2" data-number="3.3"><h2 data-number="3.3" class="anchored" data-anchor-id="price-trends-and-market-evolution">
<span class="header-section-number">3.3</span> Price Trends and Market Evolution</h2>
<div class="cell">
<details class="code-fold"><summary>Code</summary><div class="sourceCode cell-code" id="cb4"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1"></a><span class="co"># Visualizing long-term price trends with annotations for major events</span></span>
<span id="cb4-2"><a href="#cb4-2"></a>financial_events <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(</span>
<span id="cb4-3"><a href="#cb4-3"></a>  <span class="at">date =</span> <span class="fu">as.Date</span>(<span class="fu">c</span>(<span class="st">"2008-09-15"</span>, <span class="st">"2020-03-11"</span>, <span class="st">"2022-02-24"</span>)),</span>
<span id="cb4-4"><a href="#cb4-4"></a>  <span class="at">event =</span> <span class="fu">c</span>(<span class="st">"2008 Financial Crisis"</span>, <span class="st">"COVID-19 Pandemic"</span>, <span class="st">"Russia-Ukraine Conflict"</span>),</span>
<span id="cb4-5"><a href="#cb4-5"></a>  <span class="at">y_position =</span> <span class="fu">c</span>(<span class="dv">20000</span>, <span class="dv">25000</span>, <span class="dv">30000</span>)</span>
<span id="cb4-6"><a href="#cb4-6"></a>)</span>
<span id="cb4-7"><a href="#cb4-7"></a></span>
<span id="cb4-8"><a href="#cb4-8"></a><span class="fu">ggplot</span>() <span class="sc">+</span></span>
<span id="cb4-9"><a href="#cb4-9"></a>  <span class="fu">geom_line</span>(<span class="at">data =</span> market_data, </span>
<span id="cb4-10"><a href="#cb4-10"></a>            <span class="fu">aes</span>(<span class="at">x =</span> date, <span class="at">y =</span> adjusted, <span class="at">color =</span> index_name),</span>
<span id="cb4-11"><a href="#cb4-11"></a>            <span class="at">linewidth =</span> <span class="fl">0.7</span>, <span class="at">alpha =</span> <span class="fl">0.8</span>) <span class="sc">+</span></span>
<span id="cb4-12"><a href="#cb4-12"></a>  <span class="fu">geom_vline</span>(<span class="at">data =</span> financial_events, </span>
<span id="cb4-13"><a href="#cb4-13"></a>             <span class="fu">aes</span>(<span class="at">xintercept =</span> date),</span>
<span id="cb4-14"><a href="#cb4-14"></a>             <span class="at">linetype =</span> <span class="st">"dashed"</span>, <span class="at">alpha =</span> <span class="fl">0.7</span>) <span class="sc">+</span></span>
<span id="cb4-15"><a href="#cb4-15"></a>  <span class="fu">geom_text</span>(<span class="at">data =</span> financial_events,</span>
<span id="cb4-16"><a href="#cb4-16"></a>            <span class="fu">aes</span>(<span class="at">x =</span> date, <span class="at">y =</span> y_position, <span class="at">label =</span> event),</span>
<span id="cb4-17"><a href="#cb4-17"></a>            <span class="at">hjust =</span> <span class="sc">-</span><span class="fl">0.1</span>, <span class="at">vjust =</span> <span class="dv">0</span>, <span class="at">size =</span> <span class="dv">3</span>, <span class="at">angle =</span> <span class="dv">90</span>) <span class="sc">+</span></span>
<span id="cb4-18"><a href="#cb4-18"></a>  <span class="fu">labs</span>(</span>
<span id="cb4-19"><a href="#cb4-19"></a>    <span class="at">title =</span> <span class="st">"The Resilient Rise: Market Price Evolution Across Major Indices (2000-2025)"</span>,</span>
<span id="cb4-20"><a href="#cb4-20"></a>    <span class="at">subtitle =</span> <span class="st">"Tracing growth trajectories through financial crises and recoveries"</span>,</span>
<span id="cb4-21"><a href="#cb4-21"></a>    <span class="at">x =</span> <span class="st">"Year"</span>,</span>
<span id="cb4-22"><a href="#cb4-22"></a>    <span class="at">y =</span> <span class="st">"Adjusted Closing Price"</span>,</span>
<span id="cb4-23"><a href="#cb4-23"></a>    <span class="at">color =</span> <span class="st">"Index"</span>,</span>
<span id="cb4-24"><a href="#cb4-24"></a>    <span class="at">caption =</span> <span class="st">"Source: Yahoo Finance data retrieved via tidyquant package, Analysis by Zhijun H, May 2025"</span></span>
<span id="cb4-25"><a href="#cb4-25"></a>  ) <span class="sc">+</span></span>
<span id="cb4-26"><a href="#cb4-26"></a>  <span class="fu">scale_x_date</span>(<span class="at">date_breaks =</span> <span class="st">"2 years"</span>, <span class="at">date_labels =</span> <span class="st">"%Y"</span>) <span class="sc">+</span></span>
<span id="cb4-27"><a href="#cb4-27"></a>  <span class="fu">scale_y_continuous</span>(<span class="at">labels =</span> scales<span class="sc">::</span>comma) <span class="sc">+</span></span>
<span id="cb4-28"><a href="#cb4-28"></a>  <span class="fu">theme_minimal</span>() <span class="sc">+</span></span>
<span id="cb4-29"><a href="#cb4-29"></a>  <span class="fu">theme</span>(</span>
<span id="cb4-30"><a href="#cb4-30"></a>    <span class="at">legend.position =</span> <span class="st">"bottom"</span>,</span>
<span id="cb4-31"><a href="#cb4-31"></a>    <span class="at">plot.title =</span> <span class="fu">element_text</span>(<span class="at">face =</span> <span class="st">"bold"</span>),</span>
<span id="cb4-32"><a href="#cb4-32"></a>    <span class="at">panel.grid.minor =</span> <span class="fu">element_blank</span>()</span>
<span id="cb4-33"><a href="#cb4-33"></a>  )</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details><div class="cell-output-display">
<div>
<figure class="figure"><p><img src="EDA---Zhijun-He_files/figure-html/price_trends-1.png" class="img-fluid figure-img" width="960"></p>
</figure>
</div>
</div>
</div>
<p>Examining the long-term price trends reveals a fascinating story of market resilience and regional divergence. Despite facing three major global crises over the past quarter-century, all indices have demonstrated remarkable recovery capabilities, though with distinct patterns. The S&amp;P 500 stands out with its exceptional post-crisis performance, particularly following the 2008 financial crisis and the 2020 pandemic, where its recovery trajectory significantly outpaced other major markets. European indices (DAX, CAC 40, FTSE 100) show more moderate but steady growth, while Asian markets exhibit greater volatility during crisis periods but also powerful recoveries, particularly the Nikkei 225 after 2012. These divergent recovery patterns highlight the influence of regional economic policies, sector compositions, and monetary interventions on market performance.</p>
</section><section id="volatility-analysis-the-heartbeat-of-markets" class="level2" data-number="3.4"><h2 data-number="3.4" class="anchored" data-anchor-id="volatility-analysis-the-heartbeat-of-markets">
<span class="header-section-number">3.4</span> Volatility Analysis: The Heartbeat of Markets</h2>
<div class="cell">
<details class="code-fold"><summary>Code</summary><div class="sourceCode cell-code" id="cb5"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1"></a><span class="co"># Calculating daily returns and volatility metrics</span></span>
<span id="cb5-2"><a href="#cb5-2"></a>market_analysis <span class="ot">&lt;-</span> market_data <span class="sc">%&gt;%</span></span>
<span id="cb5-3"><a href="#cb5-3"></a>  <span class="fu">group_by</span>(symbol, index_name) <span class="sc">%&gt;%</span></span>
<span id="cb5-4"><a href="#cb5-4"></a>  <span class="fu">arrange</span>(date) <span class="sc">%&gt;%</span></span>
<span id="cb5-5"><a href="#cb5-5"></a>  <span class="co"># Computing daily percentage returns</span></span>
<span id="cb5-6"><a href="#cb5-6"></a>  <span class="fu">mutate</span>(</span>
<span id="cb5-7"><a href="#cb5-7"></a>    <span class="at">daily_return =</span> (adjusted <span class="sc">/</span> <span class="fu">lag</span>(adjusted) <span class="sc">-</span> <span class="dv">1</span>) <span class="sc">*</span> <span class="dv">100</span>,</span>
<span id="cb5-8"><a href="#cb5-8"></a>    <span class="co"># Adding multiple volatility measures</span></span>
<span id="cb5-9"><a href="#cb5-9"></a>    <span class="at">rolling_vol_20 =</span> <span class="fu">rollapply</span>(</span>
<span id="cb5-10"><a href="#cb5-10"></a>      daily_return,</span>
<span id="cb5-11"><a href="#cb5-11"></a>      <span class="at">width =</span> <span class="dv">20</span>,</span>
<span id="cb5-12"><a href="#cb5-12"></a>      <span class="at">FUN =</span> <span class="cf">function</span>(x) <span class="fu">sd</span>(x, <span class="at">na.rm =</span> <span class="cn">TRUE</span>) <span class="sc">*</span> <span class="fu">sqrt</span>(<span class="dv">252</span>),</span>
<span id="cb5-13"><a href="#cb5-13"></a>      <span class="at">align =</span> <span class="st">"right"</span>,</span>
<span id="cb5-14"><a href="#cb5-14"></a>      <span class="at">fill =</span> <span class="cn">NA</span></span>
<span id="cb5-15"><a href="#cb5-15"></a>    ),</span>
<span id="cb5-16"><a href="#cb5-16"></a>    <span class="at">rolling_vol_60 =</span> <span class="fu">rollapply</span>(</span>
<span id="cb5-17"><a href="#cb5-17"></a>      daily_return,</span>
<span id="cb5-18"><a href="#cb5-18"></a>      <span class="at">width =</span> <span class="dv">60</span>,</span>
<span id="cb5-19"><a href="#cb5-19"></a>      <span class="at">FUN =</span> <span class="cf">function</span>(x) <span class="fu">sd</span>(x, <span class="at">na.rm =</span> <span class="cn">TRUE</span>) <span class="sc">*</span> <span class="fu">sqrt</span>(<span class="dv">252</span>),</span>
<span id="cb5-20"><a href="#cb5-20"></a>      <span class="at">align =</span> <span class="st">"right"</span>,</span>
<span id="cb5-21"><a href="#cb5-21"></a>      <span class="at">fill =</span> <span class="cn">NA</span></span>
<span id="cb5-22"><a href="#cb5-22"></a>    ),</span>
<span id="cb5-23"><a href="#cb5-23"></a>    <span class="co"># Adding year and month for temporal analysis</span></span>
<span id="cb5-24"><a href="#cb5-24"></a>    <span class="at">year =</span> lubridate<span class="sc">::</span><span class="fu">year</span>(date),</span>
<span id="cb5-25"><a href="#cb5-25"></a>    <span class="at">month_num =</span> lubridate<span class="sc">::</span><span class="fu">month</span>(date)</span>
<span id="cb5-26"><a href="#cb5-26"></a>  ) <span class="sc">%&gt;%</span></span>
<span id="cb5-27"><a href="#cb5-27"></a>  <span class="fu">ungroup</span>() <span class="sc">%&gt;%</span></span>
<span id="cb5-28"><a href="#cb5-28"></a>  <span class="co"># Create month factor with labels</span></span>
<span id="cb5-29"><a href="#cb5-29"></a>  <span class="fu">mutate</span>(<span class="at">month =</span> <span class="fu">factor</span>(month_num, </span>
<span id="cb5-30"><a href="#cb5-30"></a>                       <span class="at">levels =</span> <span class="dv">1</span><span class="sc">:</span><span class="dv">12</span>, </span>
<span id="cb5-31"><a href="#cb5-31"></a>                       <span class="at">labels =</span> <span class="fu">c</span>(<span class="st">"Jan"</span>, <span class="st">"Feb"</span>, <span class="st">"Mar"</span>, <span class="st">"Apr"</span>, <span class="st">"May"</span>, <span class="st">"Jun"</span>, </span>
<span id="cb5-32"><a href="#cb5-32"></a>                                  <span class="st">"Jul"</span>, <span class="st">"Aug"</span>, <span class="st">"Sep"</span>, <span class="st">"Oct"</span>, <span class="st">"Nov"</span>, <span class="st">"Dec"</span>)))</span>
<span id="cb5-33"><a href="#cb5-33"></a></span>
<span id="cb5-34"><a href="#cb5-34"></a><span class="co"># Using gtsummary for a comprehensive statistical summary</span></span>
<span id="cb5-35"><a href="#cb5-35"></a>market_analysis <span class="sc">%&gt;%</span></span>
<span id="cb5-36"><a href="#cb5-36"></a>  <span class="fu">select</span>(index_name, daily_return, rolling_vol_20, rolling_vol_60) <span class="sc">%&gt;%</span></span>
<span id="cb5-37"><a href="#cb5-37"></a>  <span class="fu">tbl_summary</span>(</span>
<span id="cb5-38"><a href="#cb5-38"></a>    <span class="at">by =</span> index_name,</span>
<span id="cb5-39"><a href="#cb5-39"></a>    <span class="at">statistic =</span> <span class="fu">list</span>(</span>
<span id="cb5-40"><a href="#cb5-40"></a>      <span class="fu">all_continuous</span>() <span class="sc">~</span> <span class="st">"{mean} ({sd})"</span></span>
<span id="cb5-41"><a href="#cb5-41"></a>    ),</span>
<span id="cb5-42"><a href="#cb5-42"></a>    <span class="at">digits =</span> <span class="fu">all_continuous</span>() <span class="sc">~</span> <span class="dv">2</span></span>
<span id="cb5-43"><a href="#cb5-43"></a>  ) <span class="sc">%&gt;%</span></span>
<span id="cb5-44"><a href="#cb5-44"></a>  <span class="fu">add_stat_label</span>() <span class="sc">%&gt;%</span></span>
<span id="cb5-45"><a href="#cb5-45"></a>  <span class="fu">modify_header</span>(<span class="at">label =</span> <span class="st">"**Metric**"</span>) <span class="sc">%&gt;%</span></span>
<span id="cb5-46"><a href="#cb5-46"></a>  <span class="fu">as_kable</span>(<span class="at">caption =</span> <span class="st">"Summary Statistics of Returns and Volatility by Index"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details><div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<caption>Summary Statistics of Returns and Volatility by Index</caption>
<colgroup>
<col style="width: 15%">
<col style="width: 13%">
<col style="width: 11%">
<col style="width: 14%">
<col style="width: 15%">
<col style="width: 15%">
<col style="width: 14%">
</colgroup>
<thead><tr class="header">
<th style="text-align: left;"><strong>Metric</strong></th>
<th style="text-align: center;">
<strong>CAC 40</strong> N = 6,514</th>
<th style="text-align: center;">
<strong>DAX</strong> N = 6,479</th>
<th style="text-align: center;">
<strong>FTSE 100</strong> N = 6,452</th>
<th style="text-align: center;">
<strong>Hang Seng</strong> N = 6,322</th>
<th style="text-align: center;">
<strong>Nikkei 225</strong> N = 6,331</th>
<th style="text-align: center;">
<strong>S&amp;P 500</strong> N = 6,376</th>
</tr></thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">daily_return, Mean (SD)</td>
<td style="text-align: center;">0.01 (1.38)</td>
<td style="text-align: center;">0.03 (1.42)</td>
<td style="text-align: center;">0.01 (1.14)</td>
<td style="text-align: center;">0.01 (1.49)</td>
<td style="text-align: center;">0.02 (1.46)</td>
<td style="text-align: center;">0.03 (1.23)</td>
</tr>
<tr class="even">
<td style="text-align: left;">Unknown</td>
<td style="text-align: center;">62</td>
<td style="text-align: center;">71</td>
<td style="text-align: center;">88</td>
<td style="text-align: center;">141</td>
<td style="text-align: center;">220</td>
<td style="text-align: center;">1</td>
</tr>
<tr class="odd">
<td style="text-align: left;">rolling_vol_20, Mean (SD)</td>
<td style="text-align: center;">19.32 (10.67)</td>
<td style="text-align: center;">19.84 (10.97)</td>
<td style="text-align: center;">15.73 (9.28)</td>
<td style="text-align: center;">20.99 (10.93)</td>
<td style="text-align: center;">20.77 (10.26)</td>
<td style="text-align: center;">16.47 (10.73)</td>
</tr>
<tr class="even">
<td style="text-align: left;">Unknown</td>
<td style="text-align: center;">19</td>
<td style="text-align: center;">19</td>
<td style="text-align: center;">19</td>
<td style="text-align: center;">19</td>
<td style="text-align: center;">19</td>
<td style="text-align: center;">19</td>
</tr>
<tr class="odd">
<td style="text-align: left;">rolling_vol_60, Mean (SD)</td>
<td style="text-align: center;">19.79 (9.58)</td>
<td style="text-align: center;">20.28 (9.96)</td>
<td style="text-align: center;">16.13 (8.39)</td>
<td style="text-align: center;">21.36 (9.78)</td>
<td style="text-align: center;">21.32 (8.69)</td>
<td style="text-align: center;">16.88 (9.69)</td>
</tr>
<tr class="even">
<td style="text-align: left;">Unknown</td>
<td style="text-align: center;">59</td>
<td style="text-align: center;">59</td>
<td style="text-align: center;">59</td>
<td style="text-align: center;">59</td>
<td style="text-align: center;">59</td>
<td style="text-align: center;">59</td>
</tr>
</tbody>
</table>
</div>
</div>
<div class="cell">
<details class="code-fold"><summary>Code</summary><div class="sourceCode cell-code" id="cb6"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1"></a><span class="co"># Visualizing volatility patterns with event annotations</span></span>
<span id="cb6-2"><a href="#cb6-2"></a><span class="fu">ggplot</span>() <span class="sc">+</span></span>
<span id="cb6-3"><a href="#cb6-3"></a>  <span class="fu">geom_line</span>(<span class="at">data =</span> market_analysis <span class="sc">%&gt;%</span> <span class="fu">filter</span>(<span class="sc">!</span><span class="fu">is.na</span>(rolling_vol_20)), </span>
<span id="cb6-4"><a href="#cb6-4"></a>            <span class="fu">aes</span>(<span class="at">x =</span> date, <span class="at">y =</span> rolling_vol_20, <span class="at">color =</span> index_name),</span>
<span id="cb6-5"><a href="#cb6-5"></a>            <span class="at">alpha =</span> <span class="fl">0.8</span>) <span class="sc">+</span></span>
<span id="cb6-6"><a href="#cb6-6"></a>  <span class="fu">geom_vline</span>(<span class="at">data =</span> financial_events, </span>
<span id="cb6-7"><a href="#cb6-7"></a>             <span class="fu">aes</span>(<span class="at">xintercept =</span> date),</span>
<span id="cb6-8"><a href="#cb6-8"></a>             <span class="at">linetype =</span> <span class="st">"dashed"</span>, <span class="at">alpha =</span> <span class="fl">0.5</span>) <span class="sc">+</span></span>
<span id="cb6-9"><a href="#cb6-9"></a>  <span class="fu">labs</span>(</span>
<span id="cb6-10"><a href="#cb6-10"></a>    <span class="at">title =</span> <span class="st">"Volatility Waves: Crisis Amplification Across Global Markets"</span>,</span>
<span id="cb6-11"><a href="#cb6-11"></a>    <span class="at">subtitle =</span> <span class="st">"Tracking 20-day rolling volatility reveals distinct regional reactions to market shocks"</span>,</span>
<span id="cb6-12"><a href="#cb6-12"></a>    <span class="at">x =</span> <span class="st">"Year"</span>,</span>
<span id="cb6-13"><a href="#cb6-13"></a>    <span class="at">y =</span> <span class="st">"Annualized Volatility (%)"</span>,</span>
<span id="cb6-14"><a href="#cb6-14"></a>    <span class="at">color =</span> <span class="st">"Index"</span>,</span>
<span id="cb6-15"><a href="#cb6-15"></a>    <span class="at">caption =</span> <span class="st">"Source: Yahoo Finance data retrieved via tidyquant package, Analysis by Zhijun H, May 2025"</span></span>
<span id="cb6-16"><a href="#cb6-16"></a>  ) <span class="sc">+</span></span>
<span id="cb6-17"><a href="#cb6-17"></a>  <span class="fu">scale_x_date</span>(<span class="at">date_breaks =</span> <span class="st">"2 years"</span>, <span class="at">date_labels =</span> <span class="st">"%Y"</span>) <span class="sc">+</span></span>
<span id="cb6-18"><a href="#cb6-18"></a>  <span class="fu">scale_y_continuous</span>(<span class="at">labels =</span> scales<span class="sc">::</span><span class="fu">percent_format</span>(<span class="at">scale =</span> <span class="fl">0.01</span>)) <span class="sc">+</span></span>
<span id="cb6-19"><a href="#cb6-19"></a>  <span class="fu">theme_minimal</span>() <span class="sc">+</span></span>
<span id="cb6-20"><a href="#cb6-20"></a>  <span class="fu">theme</span>(</span>
<span id="cb6-21"><a href="#cb6-21"></a>    <span class="at">legend.position =</span> <span class="st">"bottom"</span>,</span>
<span id="cb6-22"><a href="#cb6-22"></a>    <span class="at">plot.title =</span> <span class="fu">element_text</span>(<span class="at">face =</span> <span class="st">"bold"</span>),</span>
<span id="cb6-23"><a href="#cb6-23"></a>    <span class="at">panel.grid.minor =</span> <span class="fu">element_blank</span>()</span>
<span id="cb6-24"><a href="#cb6-24"></a>  )</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details><div class="cell-output-display">
<div>
<figure class="figure"><p><img src="EDA---Zhijun-He_files/figure-html/volatility_comparison-1.png" class="img-fluid figure-img" width="960"></p>
</figure>
</div>
</div>
</div>
<p>My volatility analysis reveals striking patterns in how market uncertainty propagates across global indices. The visualization clearly shows volatility clustering—periods of high volatility tend to group together, with major spikes coinciding with the 2008 financial crisis, the 2020 pandemic, and the 2022 Russia-Ukraine conflict. Asian markets consistently exhibit higher baseline volatility, with the Hang Seng showing the highest average annualized volatility at 23.6%. In contrast, the FTSE 100 demonstrates the most stability with an average volatility of just 18.2%, reflecting the UK market’s defensive sector composition.</p>
<p>A fascinating insight emerges when examining crisis response patterns: during the 2008 financial crisis, volatility amplification was most pronounced in Western markets, while the 2020 pandemic triggered more uniform volatility spikes across all indices. The 2022 geopolitical tensions produced a more muted volatility response, suggesting markets have become more resilient to non-financial shocks in recent years. These distinct volatility signatures provide valuable context for risk management strategies across different market environments.</p>
</section><section id="market-correlations-the-global-financial-web" class="level2" data-number="3.5"><h2 data-number="3.5" class="anchored" data-anchor-id="market-correlations-the-global-financial-web">
<span class="header-section-number">3.5</span> Market Correlations: The Global Financial Web</h2>
<div class="cell">
<details class="code-fold"><summary>Code</summary><div class="sourceCode cell-code" id="cb7"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1"></a><span class="co"># Preparing daily returns by index</span></span>
<span id="cb7-2"><a href="#cb7-2"></a>daily_returns <span class="ot">&lt;-</span> market_analysis <span class="sc">%&gt;%</span></span>
<span id="cb7-3"><a href="#cb7-3"></a>  <span class="fu">select</span>(date, symbol, daily_return) <span class="sc">%&gt;%</span></span>
<span id="cb7-4"><a href="#cb7-4"></a>  <span class="fu">filter</span>(<span class="sc">!</span><span class="fu">is.na</span>(daily_return)) <span class="sc">%&gt;%</span></span>
<span id="cb7-5"><a href="#cb7-5"></a>  <span class="fu">pivot_wider</span>(</span>
<span id="cb7-6"><a href="#cb7-6"></a>    <span class="at">names_from =</span> symbol,</span>
<span id="cb7-7"><a href="#cb7-7"></a>    <span class="at">values_from =</span> daily_return</span>
<span id="cb7-8"><a href="#cb7-8"></a>  )</span>
<span id="cb7-9"><a href="#cb7-9"></a></span>
<span id="cb7-10"><a href="#cb7-10"></a><span class="co"># Calculating correlation matrix</span></span>
<span id="cb7-11"><a href="#cb7-11"></a>cor_matrix <span class="ot">&lt;-</span> <span class="fu">cor</span>(</span>
<span id="cb7-12"><a href="#cb7-12"></a>  daily_returns <span class="sc">%&gt;%</span> <span class="fu">select</span>(<span class="sc">-</span>date), </span>
<span id="cb7-13"><a href="#cb7-13"></a>  <span class="at">use =</span> <span class="st">"pairwise.complete.obs"</span></span>
<span id="cb7-14"><a href="#cb7-14"></a>)</span>
<span id="cb7-15"><a href="#cb7-15"></a></span>
<span id="cb7-16"><a href="#cb7-16"></a><span class="co"># Converting to long format for visualization</span></span>
<span id="cb7-17"><a href="#cb7-17"></a>cor_data <span class="ot">&lt;-</span> cor_matrix <span class="sc">%&gt;%</span></span>
<span id="cb7-18"><a href="#cb7-18"></a>  <span class="fu">as.data.frame</span>() <span class="sc">%&gt;%</span></span>
<span id="cb7-19"><a href="#cb7-19"></a>  <span class="fu">rownames_to_column</span>(<span class="st">"Index1"</span>) <span class="sc">%&gt;%</span></span>
<span id="cb7-20"><a href="#cb7-20"></a>  <span class="fu">pivot_longer</span>(</span>
<span id="cb7-21"><a href="#cb7-21"></a>    <span class="at">cols =</span> <span class="sc">-</span>Index1,</span>
<span id="cb7-22"><a href="#cb7-22"></a>    <span class="at">names_to =</span> <span class="st">"Index2"</span>,</span>
<span id="cb7-23"><a href="#cb7-23"></a>    <span class="at">values_to =</span> <span class="st">"Correlation"</span></span>
<span id="cb7-24"><a href="#cb7-24"></a>  )</span>
<span id="cb7-25"><a href="#cb7-25"></a></span>
<span id="cb7-26"><a href="#cb7-26"></a><span class="co"># Mapping index symbols to names</span></span>
<span id="cb7-27"><a href="#cb7-27"></a>cor_data <span class="ot">&lt;-</span> cor_data <span class="sc">%&gt;%</span></span>
<span id="cb7-28"><a href="#cb7-28"></a>  <span class="fu">mutate</span>(</span>
<span id="cb7-29"><a href="#cb7-29"></a>    <span class="at">Index1_Name =</span> indices[Index1],</span>
<span id="cb7-30"><a href="#cb7-30"></a>    <span class="at">Index2_Name =</span> indices[Index2]</span>
<span id="cb7-31"><a href="#cb7-31"></a>  )</span>
<span id="cb7-32"><a href="#cb7-32"></a></span>
<span id="cb7-33"><a href="#cb7-33"></a><span class="co"># Creating correlation heatmap</span></span>
<span id="cb7-34"><a href="#cb7-34"></a><span class="fu">ggplot</span>(cor_data, <span class="fu">aes</span>(<span class="at">x =</span> Index1_Name, <span class="at">y =</span> Index2_Name, <span class="at">fill =</span> Correlation)) <span class="sc">+</span></span>
<span id="cb7-35"><a href="#cb7-35"></a>  <span class="fu">geom_tile</span>() <span class="sc">+</span></span>
<span id="cb7-36"><a href="#cb7-36"></a>  <span class="fu">geom_text</span>(<span class="fu">aes</span>(<span class="at">label =</span> <span class="fu">round</span>(Correlation, <span class="dv">2</span>)), <span class="at">color =</span> <span class="st">"white"</span>, <span class="at">size =</span> <span class="dv">4</span>) <span class="sc">+</span></span>
<span id="cb7-37"><a href="#cb7-37"></a>  <span class="fu">scale_fill_gradient2</span>(</span>
<span id="cb7-38"><a href="#cb7-38"></a>    <span class="at">low =</span> <span class="st">"blue"</span>, <span class="at">mid =</span> <span class="st">"white"</span>, <span class="at">high =</span> <span class="st">"red"</span>,</span>
<span id="cb7-39"><a href="#cb7-39"></a>    <span class="at">midpoint =</span> <span class="fl">0.5</span>, <span class="at">limits =</span> <span class="fu">c</span>(<span class="dv">0</span>, <span class="dv">1</span>)</span>
<span id="cb7-40"><a href="#cb7-40"></a>  ) <span class="sc">+</span></span>
<span id="cb7-41"><a href="#cb7-41"></a>  <span class="fu">labs</span>(</span>
<span id="cb7-42"><a href="#cb7-42"></a>    <span class="at">title =</span> <span class="st">"The Global Financial Web: Market Interconnections Revealed"</span>,</span>
<span id="cb7-43"><a href="#cb7-43"></a>    <span class="at">subtitle =</span> <span class="st">"European markets show strongest cross-correlations while Asian indices maintain relative independence"</span>,</span>
<span id="cb7-44"><a href="#cb7-44"></a>    <span class="at">x =</span> <span class="cn">NULL</span>, <span class="at">y =</span> <span class="cn">NULL</span>,</span>
<span id="cb7-45"><a href="#cb7-45"></a>    <span class="at">caption =</span> <span class="st">"Source: Yahoo Finance data retrieved via tidyquant package, Analysis by Zhijun H, May 2025"</span></span>
<span id="cb7-46"><a href="#cb7-46"></a>  ) <span class="sc">+</span></span>
<span id="cb7-47"><a href="#cb7-47"></a>  <span class="fu">theme_minimal</span>() <span class="sc">+</span></span>
<span id="cb7-48"><a href="#cb7-48"></a>  <span class="fu">theme</span>(</span>
<span id="cb7-49"><a href="#cb7-49"></a>    <span class="at">axis.text.x =</span> <span class="fu">element_text</span>(<span class="at">angle =</span> <span class="dv">45</span>, <span class="at">hjust =</span> <span class="dv">1</span>),</span>
<span id="cb7-50"><a href="#cb7-50"></a>    <span class="at">plot.title =</span> <span class="fu">element_text</span>(<span class="at">face =</span> <span class="st">"bold"</span>)</span>
<span id="cb7-51"><a href="#cb7-51"></a>  )</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details><div class="cell-output-display">
<div>
<figure class="figure"><p><img src="EDA---Zhijun-He_files/figure-html/correlation_analysis-1.png" class="img-fluid figure-img" width="960"></p>
</figure>
</div>
</div>
</div>
<p>My correlation analysis uncovers the complex interdependencies within the global financial system. European markets form the most tightly connected cluster, with the DAX, CAC 40, and FTSE 100 showing remarkably strong correlations (0.78-0.91), reflecting their geographic proximity, shared regulatory environments, and economic integration through the European Union.</p>
<p>The S&amp;P 500 maintains moderate to strong correlations with all markets (0.57-0.65), underscoring its central role in the global financial system and its influence on worldwide market sentiment. Most notable is the relative independence of Asian markets, particularly the Hang Seng, which shows the weakest correlations with other indices (0.32-0.45). This suggests substantial diversification benefits for global portfolios that include exposure to these Asian markets.</p>
<p>These correlation patterns have important implications for portfolio construction, risk management, and for understanding how financial shocks propagate through the global system. The strongest links appear between markets with overlapping trading hours, suggesting that real-time information transmission plays a key role in driving these relationships.</p>
</section><section id="temporal-patterns-cycles-and-seasonality" class="level2" data-number="3.6"><h2 data-number="3.6" class="anchored" data-anchor-id="temporal-patterns-cycles-and-seasonality">
<span class="header-section-number">3.6</span> Temporal Patterns: Cycles and Seasonality</h2>
<div class="cell">
<details class="code-fold"><summary>Code</summary><div class="sourceCode cell-code" id="cb8"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1"></a><span class="co"># Analyzing volatility by year</span></span>
<span id="cb8-2"><a href="#cb8-2"></a>yearly_volatility <span class="ot">&lt;-</span> market_analysis <span class="sc">%&gt;%</span></span>
<span id="cb8-3"><a href="#cb8-3"></a>  <span class="fu">filter</span>(<span class="sc">!</span><span class="fu">is.na</span>(daily_return)) <span class="sc">%&gt;%</span></span>
<span id="cb8-4"><a href="#cb8-4"></a>  <span class="fu">group_by</span>(index_name, year) <span class="sc">%&gt;%</span></span>
<span id="cb8-5"><a href="#cb8-5"></a>  <span class="fu">summarize</span>(</span>
<span id="cb8-6"><a href="#cb8-6"></a>    <span class="at">annual_volatility =</span> <span class="fu">sd</span>(daily_return, <span class="at">na.rm =</span> <span class="cn">TRUE</span>) <span class="sc">*</span> <span class="fu">sqrt</span>(<span class="dv">252</span>),</span>
<span id="cb8-7"><a href="#cb8-7"></a>    <span class="at">avg_return =</span> <span class="fu">mean</span>(daily_return, <span class="at">na.rm =</span> <span class="cn">TRUE</span>),</span>
<span id="cb8-8"><a href="#cb8-8"></a>    <span class="at">.groups =</span> <span class="st">"drop"</span></span>
<span id="cb8-9"><a href="#cb8-9"></a>  )</span>
<span id="cb8-10"><a href="#cb8-10"></a></span>
<span id="cb8-11"><a href="#cb8-11"></a><span class="co"># Creating plot of yearly volatility</span></span>
<span id="cb8-12"><a href="#cb8-12"></a>yearly_vol_plot <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(yearly_volatility, </span>
<span id="cb8-13"><a href="#cb8-13"></a>                          <span class="fu">aes</span>(<span class="at">x =</span> year, <span class="at">y =</span> annual_volatility, <span class="at">color =</span> index_name)) <span class="sc">+</span></span>
<span id="cb8-14"><a href="#cb8-14"></a>  <span class="fu">geom_line</span>(<span class="at">linewidth =</span> <span class="dv">1</span>) <span class="sc">+</span></span>
<span id="cb8-15"><a href="#cb8-15"></a>  <span class="fu">geom_point</span>(<span class="at">size =</span> <span class="dv">2</span>) <span class="sc">+</span></span>
<span id="cb8-16"><a href="#cb8-16"></a>  <span class="fu">labs</span>(</span>
<span id="cb8-17"><a href="#cb8-17"></a>    <span class="at">title =</span> <span class="st">"Yearly Volatility Evolution: Crisis Years and Recovery Periods"</span>,</span>
<span id="cb8-18"><a href="#cb8-18"></a>    <span class="at">x =</span> <span class="st">"Year"</span>, </span>
<span id="cb8-19"><a href="#cb8-19"></a>    <span class="at">y =</span> <span class="st">"Annualized Volatility (%)"</span>,</span>
<span id="cb8-20"><a href="#cb8-20"></a>    <span class="at">color =</span> <span class="st">"Index"</span></span>
<span id="cb8-21"><a href="#cb8-21"></a>  ) <span class="sc">+</span></span>
<span id="cb8-22"><a href="#cb8-22"></a>  <span class="fu">scale_y_continuous</span>(<span class="at">labels =</span> scales<span class="sc">::</span><span class="fu">percent_format</span>(<span class="at">scale =</span> <span class="fl">0.01</span>)) <span class="sc">+</span></span>
<span id="cb8-23"><a href="#cb8-23"></a>  <span class="fu">theme_minimal</span>() <span class="sc">+</span></span>
<span id="cb8-24"><a href="#cb8-24"></a>  <span class="fu">theme</span>(<span class="at">legend.position =</span> <span class="st">"bottom"</span>)</span>
<span id="cb8-25"><a href="#cb8-25"></a></span>
<span id="cb8-26"><a href="#cb8-26"></a><span class="co"># Analyzing monthly patterns</span></span>
<span id="cb8-27"><a href="#cb8-27"></a>monthly_patterns <span class="ot">&lt;-</span> market_analysis <span class="sc">%&gt;%</span></span>
<span id="cb8-28"><a href="#cb8-28"></a>  <span class="fu">filter</span>(<span class="sc">!</span><span class="fu">is.na</span>(daily_return)) <span class="sc">%&gt;%</span></span>
<span id="cb8-29"><a href="#cb8-29"></a>  <span class="fu">group_by</span>(index_name, month) <span class="sc">%&gt;%</span></span>
<span id="cb8-30"><a href="#cb8-30"></a>  <span class="fu">summarize</span>(</span>
<span id="cb8-31"><a href="#cb8-31"></a>    <span class="at">avg_return =</span> <span class="fu">mean</span>(daily_return, <span class="at">na.rm =</span> <span class="cn">TRUE</span>),</span>
<span id="cb8-32"><a href="#cb8-32"></a>    <span class="at">volatility =</span> <span class="fu">sd</span>(daily_return, <span class="at">na.rm =</span> <span class="cn">TRUE</span>),</span>
<span id="cb8-33"><a href="#cb8-33"></a>    <span class="at">sharpe =</span> avg_return <span class="sc">/</span> volatility,</span>
<span id="cb8-34"><a href="#cb8-34"></a>    <span class="at">.groups =</span> <span class="st">"drop"</span></span>
<span id="cb8-35"><a href="#cb8-35"></a>  )</span>
<span id="cb8-36"><a href="#cb8-36"></a></span>
<span id="cb8-37"><a href="#cb8-37"></a><span class="co"># Creating plot of monthly returns</span></span>
<span id="cb8-38"><a href="#cb8-38"></a>monthly_return_plot <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(monthly_patterns, </span>
<span id="cb8-39"><a href="#cb8-39"></a>                             <span class="fu">aes</span>(<span class="at">x =</span> month, <span class="at">y =</span> avg_return, <span class="at">fill =</span> index_name)) <span class="sc">+</span></span>
<span id="cb8-40"><a href="#cb8-40"></a>  <span class="fu">geom_col</span>(<span class="at">position =</span> <span class="st">"dodge"</span>) <span class="sc">+</span></span>
<span id="cb8-41"><a href="#cb8-41"></a>  <span class="fu">labs</span>(</span>
<span id="cb8-42"><a href="#cb8-42"></a>    <span class="at">title =</span> <span class="st">"Monthly Return Patterns"</span>,</span>
<span id="cb8-43"><a href="#cb8-43"></a>    <span class="at">x =</span> <span class="st">"Month"</span>, </span>
<span id="cb8-44"><a href="#cb8-44"></a>    <span class="at">y =</span> <span class="st">"Average Daily Return (%)"</span>,</span>
<span id="cb8-45"><a href="#cb8-45"></a>    <span class="at">fill =</span> <span class="st">"Index"</span></span>
<span id="cb8-46"><a href="#cb8-46"></a>  ) <span class="sc">+</span></span>
<span id="cb8-47"><a href="#cb8-47"></a>  <span class="fu">theme_minimal</span>() <span class="sc">+</span></span>
<span id="cb8-48"><a href="#cb8-48"></a>  <span class="fu">theme</span>(<span class="at">legend.position =</span> <span class="st">"bottom"</span>)</span>
<span id="cb8-49"><a href="#cb8-49"></a></span>
<span id="cb8-50"><a href="#cb8-50"></a><span class="co"># Creating plot of monthly volatility</span></span>
<span id="cb8-51"><a href="#cb8-51"></a>monthly_vol_plot <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(monthly_patterns, </span>
<span id="cb8-52"><a href="#cb8-52"></a>                          <span class="fu">aes</span>(<span class="at">x =</span> month, <span class="at">y =</span> volatility, <span class="at">fill =</span> index_name)) <span class="sc">+</span></span>
<span id="cb8-53"><a href="#cb8-53"></a>  <span class="fu">geom_col</span>(<span class="at">position =</span> <span class="st">"dodge"</span>) <span class="sc">+</span></span>
<span id="cb8-54"><a href="#cb8-54"></a>  <span class="fu">labs</span>(</span>
<span id="cb8-55"><a href="#cb8-55"></a>    <span class="at">title =</span> <span class="st">"Monthly Volatility Signatures"</span>,</span>
<span id="cb8-56"><a href="#cb8-56"></a>    <span class="at">x =</span> <span class="st">"Month"</span>, </span>
<span id="cb8-57"><a href="#cb8-57"></a>    <span class="at">y =</span> <span class="st">"Daily Return Volatility (%)"</span>,</span>
<span id="cb8-58"><a href="#cb8-58"></a>    <span class="at">fill =</span> <span class="st">"Index"</span></span>
<span id="cb8-59"><a href="#cb8-59"></a>  ) <span class="sc">+</span></span>
<span id="cb8-60"><a href="#cb8-60"></a>  <span class="fu">theme_minimal</span>() <span class="sc">+</span></span>
<span id="cb8-61"><a href="#cb8-61"></a>  <span class="fu">theme</span>(<span class="at">legend.position =</span> <span class="st">"bottom"</span>)</span>
<span id="cb8-62"><a href="#cb8-62"></a></span>
<span id="cb8-63"><a href="#cb8-63"></a><span class="co"># Combining plots using patchwork package</span></span>
<span id="cb8-64"><a href="#cb8-64"></a><span class="fu">library</span>(patchwork)</span>
<span id="cb8-65"><a href="#cb8-65"></a>(yearly_vol_plot <span class="sc">/</span> (monthly_return_plot <span class="sc">|</span> monthly_vol_plot)) <span class="sc">+</span></span>
<span id="cb8-66"><a href="#cb8-66"></a>  <span class="fu">plot_annotation</span>(</span>
<span id="cb8-67"><a href="#cb8-67"></a>    <span class="at">title =</span> <span class="st">"Temporal Market Rhythms: Annual Cycles and Monthly Patterns"</span>,</span>
<span id="cb8-68"><a href="#cb8-68"></a>    <span class="at">subtitle =</span> <span class="st">"Volatility ebbs and flows follow both crisis-driven and seasonal patterns"</span>,</span>
<span id="cb8-69"><a href="#cb8-69"></a>    <span class="at">caption =</span> <span class="st">"Source: Yahoo Finance data retrieved via tidyquant package, Analysis by Zhijun H, May 2025"</span></span>
<span id="cb8-70"><a href="#cb8-70"></a>  )</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details><div class="cell-output-display">
<div>
<figure class="figure"><p><img src="EDA---Zhijun-He_files/figure-html/temporal_analysis-1.png" class="img-fluid figure-img" width="960"></p>
</figure>
</div>
</div>
</div>
<p>My temporal analysis reveals fascinating cyclical patterns in market behavior across different time horizons. The yearly volatility plot demonstrates clear crisis-driven cycles, with all markets experiencing synchronized volatility spikes during 2008, 2020, and to a lesser extent, 2022. Interestingly, I observe that Asian markets tend to maintain elevated volatility for longer periods after major shocks, while Western markets, particularly the S&amp;P 500, show more rapid volatility normalization.</p>
<p>At the monthly level, distinct seasonal patterns emerge that have important implications for trading strategies. April emerges as the strongest month for returns across most indices, aligning with the “Sell in May” investment adage. September and October consistently show elevated volatility across all markets—a pattern often referred to as the “October effect” in financial literature. The Hang Seng exhibits particularly pronounced monthly return dispersion, suggesting greater sensitivity to seasonal factors.</p>
<p>These temporal signatures provide valuable inputs for market timing strategies and risk management approaches, as they reveal predictable windows of heightened uncertainty and potential return opportunities across the global market landscape.</p>
</section><section id="advanced-volatility-analysis-risk-regimes" class="level2" data-number="3.7"><h2 data-number="3.7" class="anchored" data-anchor-id="advanced-volatility-analysis-risk-regimes">
<span class="header-section-number">3.7</span> Advanced Volatility Analysis: Risk Regimes</h2>
<div class="cell">
<details class="code-fold"><summary>Code</summary><div class="sourceCode cell-code" id="cb9"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1"></a><span class="co"># Creating volatility clusters</span></span>
<span id="cb9-2"><a href="#cb9-2"></a>volatility_clusters <span class="ot">&lt;-</span> market_analysis <span class="sc">%&gt;%</span></span>
<span id="cb9-3"><a href="#cb9-3"></a>  <span class="fu">filter</span>(<span class="sc">!</span><span class="fu">is.na</span>(rolling_vol_20)) <span class="sc">%&gt;%</span></span>
<span id="cb9-4"><a href="#cb9-4"></a>  <span class="fu">mutate</span>(</span>
<span id="cb9-5"><a href="#cb9-5"></a>    <span class="at">vol_regime =</span> <span class="fu">case_when</span>(</span>
<span id="cb9-6"><a href="#cb9-6"></a>      rolling_vol_20 <span class="sc">&lt;=</span> <span class="fu">quantile</span>(rolling_vol_20, <span class="fl">0.33</span>, <span class="at">na.rm =</span> <span class="cn">TRUE</span>) <span class="sc">~</span> <span class="st">"Low"</span>,</span>
<span id="cb9-7"><a href="#cb9-7"></a>      rolling_vol_20 <span class="sc">&lt;=</span> <span class="fu">quantile</span>(rolling_vol_20, <span class="fl">0.67</span>, <span class="at">na.rm =</span> <span class="cn">TRUE</span>) <span class="sc">~</span> <span class="st">"Medium"</span>,</span>
<span id="cb9-8"><a href="#cb9-8"></a>      <span class="cn">TRUE</span> <span class="sc">~</span> <span class="st">"High"</span></span>
<span id="cb9-9"><a href="#cb9-9"></a>    )</span>
<span id="cb9-10"><a href="#cb9-10"></a>  )</span>
<span id="cb9-11"><a href="#cb9-11"></a></span>
<span id="cb9-12"><a href="#cb9-12"></a><span class="co"># Analyzing return characteristics by volatility regime</span></span>
<span id="cb9-13"><a href="#cb9-13"></a>regime_analysis <span class="ot">&lt;-</span> volatility_clusters <span class="sc">%&gt;%</span></span>
<span id="cb9-14"><a href="#cb9-14"></a>  <span class="fu">group_by</span>(index_name, vol_regime) <span class="sc">%&gt;%</span></span>
<span id="cb9-15"><a href="#cb9-15"></a>  <span class="fu">summarize</span>(</span>
<span id="cb9-16"><a href="#cb9-16"></a>    <span class="at">avg_return =</span> <span class="fu">mean</span>(daily_return, <span class="at">na.rm =</span> <span class="cn">TRUE</span>),</span>
<span id="cb9-17"><a href="#cb9-17"></a>    <span class="at">median_return =</span> <span class="fu">median</span>(daily_return, <span class="at">na.rm =</span> <span class="cn">TRUE</span>),</span>
<span id="cb9-18"><a href="#cb9-18"></a>    <span class="at">return_sd =</span> <span class="fu">sd</span>(daily_return, <span class="at">na.rm =</span> <span class="cn">TRUE</span>),</span>
<span id="cb9-19"><a href="#cb9-19"></a>    <span class="at">days =</span> <span class="fu">n</span>(),</span>
<span id="cb9-20"><a href="#cb9-20"></a>    <span class="at">pct_days =</span> <span class="fu">n</span>() <span class="sc">/</span> <span class="fu">sum</span>(<span class="sc">!</span><span class="fu">is.na</span>(market_analysis<span class="sc">$</span>rolling_vol_20)) <span class="sc">*</span> <span class="dv">100</span>,</span>
<span id="cb9-21"><a href="#cb9-21"></a>    <span class="at">.groups =</span> <span class="st">"drop"</span></span>
<span id="cb9-22"><a href="#cb9-22"></a>  )</span>
<span id="cb9-23"><a href="#cb9-23"></a></span>
<span id="cb9-24"><a href="#cb9-24"></a><span class="co"># Creating visualization of returns by volatility regime</span></span>
<span id="cb9-25"><a href="#cb9-25"></a><span class="fu">ggplot</span>(regime_analysis, </span>
<span id="cb9-26"><a href="#cb9-26"></a>       <span class="fu">aes</span>(<span class="at">x =</span> vol_regime, <span class="at">y =</span> avg_return, <span class="at">fill =</span> index_name)) <span class="sc">+</span></span>
<span id="cb9-27"><a href="#cb9-27"></a>  <span class="fu">geom_col</span>(<span class="at">position =</span> <span class="st">"dodge"</span>) <span class="sc">+</span></span>
<span id="cb9-28"><a href="#cb9-28"></a>  <span class="fu">geom_errorbar</span>(</span>
<span id="cb9-29"><a href="#cb9-29"></a>    <span class="fu">aes</span>(<span class="at">ymin =</span> avg_return <span class="sc">-</span> return_sd<span class="sc">/</span><span class="fu">sqrt</span>(days), </span>
<span id="cb9-30"><a href="#cb9-30"></a>        <span class="at">ymax =</span> avg_return <span class="sc">+</span> return_sd<span class="sc">/</span><span class="fu">sqrt</span>(days)),</span>
<span id="cb9-31"><a href="#cb9-31"></a>    <span class="at">position =</span> <span class="fu">position_dodge</span>(<span class="fl">0.9</span>),</span>
<span id="cb9-32"><a href="#cb9-32"></a>    <span class="at">width =</span> <span class="fl">0.2</span></span>
<span id="cb9-33"><a href="#cb9-33"></a>  ) <span class="sc">+</span></span>
<span id="cb9-34"><a href="#cb9-34"></a>  <span class="fu">labs</span>(</span>
<span id="cb9-35"><a href="#cb9-35"></a>    <span class="at">title =</span> <span class="st">"The Volatility Paradox: Return Patterns Across Risk Regimes"</span>,</span>
<span id="cb9-36"><a href="#cb9-36"></a>    <span class="at">subtitle =</span> <span class="st">"Asian markets show surprising resilience during high volatility periods"</span>,</span>
<span id="cb9-37"><a href="#cb9-37"></a>    <span class="at">x =</span> <span class="st">"Volatility Regime"</span>,</span>
<span id="cb9-38"><a href="#cb9-38"></a>    <span class="at">y =</span> <span class="st">"Average Daily Return (%)"</span>,</span>
<span id="cb9-39"><a href="#cb9-39"></a>    <span class="at">fill =</span> <span class="st">"Index"</span>,</span>
<span id="cb9-40"><a href="#cb9-40"></a>    <span class="at">caption =</span> <span class="st">"Source: Yahoo Finance data retrieved via tidyquant package, Analysis by Zhijun H, May 2025"</span></span>
<span id="cb9-41"><a href="#cb9-41"></a>  ) <span class="sc">+</span></span>
<span id="cb9-42"><a href="#cb9-42"></a>  <span class="fu">facet_wrap</span>(<span class="sc">~</span>index_name, <span class="at">scales =</span> <span class="st">"free_y"</span>) <span class="sc">+</span></span>
<span id="cb9-43"><a href="#cb9-43"></a>  <span class="fu">theme_minimal</span>() <span class="sc">+</span></span>
<span id="cb9-44"><a href="#cb9-44"></a>  <span class="fu">theme</span>(</span>
<span id="cb9-45"><a href="#cb9-45"></a>    <span class="at">legend.position =</span> <span class="st">"none"</span>,</span>
<span id="cb9-46"><a href="#cb9-46"></a>    <span class="at">plot.title =</span> <span class="fu">element_text</span>(<span class="at">face =</span> <span class="st">"bold"</span>)</span>
<span id="cb9-47"><a href="#cb9-47"></a>  )</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details><div class="cell-output-display">
<div>
<figure class="figure"><p><img src="EDA---Zhijun-He_files/figure-html/advanced_volatility-1.png" class="img-fluid figure-img" width="960"></p>
</figure>
</div>
</div>
</div>
<p>My analysis of market behavior across different volatility regimes reveals counterintuitive patterns that challenge conventional risk-return assumptions. While finance theory suggests higher risk should be compensated with higher returns, I find this relationship doesn’t hold uniformly across all markets and volatility environments.</p>
<p>Western indices, particularly the S&amp;P 500 and DAX, show the expected negative relationship between volatility and returns—their average daily returns deteriorate as volatility increases, with the S&amp;P 500 actually showing negative average returns during high-volatility periods. This pattern aligns with the “fear premium” concept, where market uncertainty drives risk aversion and equity selling.</p>
<p>Surprisingly, Asian markets demonstrate unusual resilience during turbulent periods. The Hang Seng and Nikkei 225 maintain relatively stable returns across volatility regimes, with only modest deterioration in high-volatility environments. This suggests fundamentally different investor behavior in these markets, possibly reflecting greater retail investor participation, different institutional structures, or varying monetary policy approaches.</p>
<p>These insights have significant implications for risk management strategies and suggest that optimal portfolio allocations should shift toward Asian exposure during periods of elevated global market stress.</p>
</section><section id="summary-statistics-and-performance-metrics" class="level2" data-number="3.8"><h2 data-number="3.8" class="anchored" data-anchor-id="summary-statistics-and-performance-metrics">
<span class="header-section-number">3.8</span> Summary Statistics and Performance Metrics</h2>
<div class="cell">
<details class="code-fold"><summary>Code</summary><div class="sourceCode cell-code" id="cb10"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1"></a><span class="co"># Generating comprehensive summary statistics</span></span>
<span id="cb10-2"><a href="#cb10-2"></a>market_summary <span class="ot">&lt;-</span> market_analysis <span class="sc">%&gt;%</span></span>
<span id="cb10-3"><a href="#cb10-3"></a>  <span class="fu">group_by</span>(index_name) <span class="sc">%&gt;%</span></span>
<span id="cb10-4"><a href="#cb10-4"></a>  <span class="fu">summarize</span>(</span>
<span id="cb10-5"><a href="#cb10-5"></a>    <span class="at">avg_daily_return =</span> <span class="fu">mean</span>(daily_return, <span class="at">na.rm =</span> <span class="cn">TRUE</span>),</span>
<span id="cb10-6"><a href="#cb10-6"></a>    <span class="at">median_daily_return =</span> <span class="fu">median</span>(daily_return, <span class="at">na.rm =</span> <span class="cn">TRUE</span>),</span>
<span id="cb10-7"><a href="#cb10-7"></a>    <span class="at">volatility =</span> <span class="fu">sd</span>(daily_return, <span class="at">na.rm =</span> <span class="cn">TRUE</span>),</span>
<span id="cb10-8"><a href="#cb10-8"></a>    <span class="at">annualized_return =</span> <span class="fu">mean</span>(daily_return, <span class="at">na.rm =</span> <span class="cn">TRUE</span>) <span class="sc">*</span> <span class="dv">252</span>,</span>
<span id="cb10-9"><a href="#cb10-9"></a>    <span class="at">annualized_volatility =</span> <span class="fu">sd</span>(daily_return, <span class="at">na.rm =</span> <span class="cn">TRUE</span>) <span class="sc">*</span> <span class="fu">sqrt</span>(<span class="dv">252</span>),</span>
<span id="cb10-10"><a href="#cb10-10"></a>    <span class="at">min_return =</span> <span class="fu">min</span>(daily_return, <span class="at">na.rm =</span> <span class="cn">TRUE</span>),</span>
<span id="cb10-11"><a href="#cb10-11"></a>    <span class="at">max_return =</span> <span class="fu">max</span>(daily_return, <span class="at">na.rm =</span> <span class="cn">TRUE</span>),</span>
<span id="cb10-12"><a href="#cb10-12"></a>    <span class="at">sharpe_ratio =</span> (<span class="fu">mean</span>(daily_return, <span class="at">na.rm =</span> <span class="cn">TRUE</span>) <span class="sc">*</span> <span class="dv">252</span>) <span class="sc">/</span> </span>
<span id="cb10-13"><a href="#cb10-13"></a>                   (<span class="fu">sd</span>(daily_return, <span class="at">na.rm =</span> <span class="cn">TRUE</span>) <span class="sc">*</span> <span class="fu">sqrt</span>(<span class="dv">252</span>)),</span>
<span id="cb10-14"><a href="#cb10-14"></a>    <span class="co"># Removed moments package dependency</span></span>
<span id="cb10-15"><a href="#cb10-15"></a>    <span class="at">data_completeness =</span> <span class="dv">1</span> <span class="sc">-</span> (<span class="fu">sum</span>(<span class="fu">is.na</span>(daily_return)) <span class="sc">/</span> <span class="fu">n</span>()),</span>
<span id="cb10-16"><a href="#cb10-16"></a>    <span class="at">win_rate =</span> <span class="fu">mean</span>(daily_return <span class="sc">&gt;</span> <span class="dv">0</span>, <span class="at">na.rm =</span> <span class="cn">TRUE</span>) <span class="sc">*</span> <span class="dv">100</span></span>
<span id="cb10-17"><a href="#cb10-17"></a>  ) <span class="sc">%&gt;%</span></span>
<span id="cb10-18"><a href="#cb10-18"></a>  <span class="fu">arrange</span>(<span class="fu">desc</span>(sharpe_ratio))</span>
<span id="cb10-19"><a href="#cb10-19"></a></span>
<span id="cb10-20"><a href="#cb10-20"></a><span class="co"># Displaying summary statistics</span></span>
<span id="cb10-21"><a href="#cb10-21"></a>market_summary <span class="sc">%&gt;%</span></span>
<span id="cb10-22"><a href="#cb10-22"></a>  <span class="fu">select</span>(index_name, avg_daily_return, annualized_return, </span>
<span id="cb10-23"><a href="#cb10-23"></a>         annualized_volatility, sharpe_ratio, win_rate) <span class="sc">%&gt;%</span></span>
<span id="cb10-24"><a href="#cb10-24"></a>  knitr<span class="sc">::</span><span class="fu">kable</span>(</span>
<span id="cb10-25"><a href="#cb10-25"></a>    <span class="at">digits =</span> <span class="dv">4</span>,</span>
<span id="cb10-26"><a href="#cb10-26"></a>    <span class="at">caption =</span> <span class="st">"Key Performance Metrics by Index (2000-Present)"</span></span>
<span id="cb10-27"><a href="#cb10-27"></a>  )</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details><div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<caption>Key Performance Metrics by Index (2000-Present)</caption>
<colgroup>
<col style="width: 12%">
<col style="width: 18%">
<col style="width: 20%">
<col style="width: 24%">
<col style="width: 14%">
<col style="width: 10%">
</colgroup>
<thead><tr class="header">
<th style="text-align: left;">index_name</th>
<th style="text-align: right;">avg_daily_return</th>
<th style="text-align: right;">annualized_return</th>
<th style="text-align: right;">annualized_volatility</th>
<th style="text-align: right;">sharpe_ratio</th>
<th style="text-align: right;">win_rate</th>
</tr></thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">S&amp;P 500</td>
<td style="text-align: right;">0.0289</td>
<td style="text-align: right;">7.2811</td>
<td style="text-align: right;">19.5233</td>
<td style="text-align: right;">0.3729</td>
<td style="text-align: right;">53.6157</td>
</tr>
<tr class="even">
<td style="text-align: left;">DAX</td>
<td style="text-align: right;">0.0279</td>
<td style="text-align: right;">7.0248</td>
<td style="text-align: right;">22.6139</td>
<td style="text-align: right;">0.3106</td>
<td style="text-align: right;">53.0743</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Nikkei 225</td>
<td style="text-align: right;">0.0151</td>
<td style="text-align: right;">3.7998</td>
<td style="text-align: right;">23.1505</td>
<td style="text-align: right;">0.1641</td>
<td style="text-align: right;">51.7591</td>
</tr>
<tr class="even">
<td style="text-align: left;">CAC 40</td>
<td style="text-align: right;">0.0122</td>
<td style="text-align: right;">3.0824</td>
<td style="text-align: right;">21.9737</td>
<td style="text-align: right;">0.1403</td>
<td style="text-align: right;">51.6894</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Hang Seng</td>
<td style="text-align: right;">0.0120</td>
<td style="text-align: right;">3.0266</td>
<td style="text-align: right;">23.6495</td>
<td style="text-align: right;">0.1280</td>
<td style="text-align: right;">51.0759</td>
</tr>
<tr class="even">
<td style="text-align: left;">FTSE 100</td>
<td style="text-align: right;">0.0090</td>
<td style="text-align: right;">2.2796</td>
<td style="text-align: right;">18.1547</td>
<td style="text-align: right;">0.1256</td>
<td style="text-align: right;">51.9799</td>
</tr>
</tbody>
</table>
</div>
</div>
</section><section id="insights-and-conclusions" class="level2" data-number="3.9"><h2 data-number="3.9" class="anchored" data-anchor-id="insights-and-conclusions">
<span class="header-section-number">3.9</span> Insights and Conclusions</h2>
<p>My comprehensive analysis of global market indices from 2000 to 2025 reveals several key insights that inform our understanding of volatility patterns and market behavior:</p>
<ol type="1">
<li><p><strong>Performance Hierarchy</strong>: The S&amp;P 500 has demonstrated superior risk-adjusted returns with the highest Sharpe ratio (0.3729) among all indices, followed by the German DAX (0.3106). Despite experiencing significant crisis periods, US equities have shown exceptional resilience and growth momentum, particularly in post-crisis recovery phases.</p></li>
<li><p><strong>Volatility Fingerprints</strong>: Each market exhibits a distinct volatility signature, with Asian indices showing consistently higher volatility (Hang Seng at 23.65% annualized) compared to their Western counterparts. The FTSE 100 stands as the most stable major index with 18.15% annualized volatility, reflecting its defensive sector composition.</p></li>
<li><p><strong>Global Interconnectedness</strong>: The correlation analysis reveals a financial ecosystem where European markets form the most tightly interconnected cluster (correlations exceeding 0.78), while Asian markets maintain relative independence. The S&amp;P 500’s moderate to strong correlations with all indices highlight its central role in the global financial architecture.</p></li>
<li><p><strong>Temporal Patterns</strong>: Clear seasonal effects emerge across markets, with September-October showing elevated volatility and April delivering the strongest returns. These patterns persist across market cycles and provide actionable insights for timing investment decisions.</p></li>
<li><p><strong>Volatility Regimes</strong>: Different markets show varying responses to high-volatility environments, with Asian indices demonstrating surprising resilience compared to Western markets. This challenges conventional risk-return assumptions and suggests opportunities for strategic allocation shifts during market stress periods.</p></li>
</ol>
<p>These findings provide valuable context for our group’s research on volatility prediction and trading strategies. The identified patterns suggest that successful approaches should incorporate market-specific volatility characteristics, account for regional interconnections, and adapt to changing volatility regimes. As markets continue to evolve, understanding these fundamental volatility dynamics will remain crucial for effective risk management and investment decision-making.</p>


<!-- -->

</section></main><!-- /main --><script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const disableStylesheet = (stylesheets) => {
    for (let i=0; i < stylesheets.length; i++) {
      const stylesheet = stylesheets[i];
      stylesheet.rel = 'prefetch';
    }
  }
  const enableStylesheet = (stylesheets) => {
    for (let i=0; i < stylesheets.length; i++) {
      const stylesheet = stylesheets[i];
      stylesheet.rel = 'stylesheet';
    }
  }
  const manageTransitions = (selector, allowTransitions) => {
    const els = window.document.querySelectorAll(selector);
    for (let i=0; i < els.length; i++) {
      const el = els[i];
      if (allowTransitions) {
        el.classList.remove('notransition');
      } else {
        el.classList.add('notransition');
      }
    }
  }
  const toggleGiscusIfUsed = (isAlternate, darkModeDefault) => {
    const baseTheme = document.querySelector('#giscus-base-theme')?.value ?? 'light';
    const alternateTheme = document.querySelector('#giscus-alt-theme')?.value ?? 'dark';
    let newTheme = '';
    if(darkModeDefault) {
      newTheme = isAlternate ? baseTheme : alternateTheme;
    } else {
      newTheme = isAlternate ? alternateTheme : baseTheme;
    }
    const changeGiscusTheme = () => {
      // From: https://github.com/giscus/giscus/issues/336
      const sendMessage = (message) => {
        const iframe = document.querySelector('iframe.giscus-frame');
        if (!iframe) return;
        iframe.contentWindow.postMessage({ giscus: message }, 'https://giscus.app');
      }
      sendMessage({
        setConfig: {
          theme: newTheme
        }
      });
    }
    const isGiscussLoaded = window.document.querySelector('iframe.giscus-frame') !== null;
    if (isGiscussLoaded) {
      changeGiscusTheme();
    }
  }
  const toggleColorMode = (alternate) => {
    // Switch the stylesheets
    const alternateStylesheets = window.document.querySelectorAll('link.quarto-color-scheme.quarto-color-alternate');
    manageTransitions('#quarto-margin-sidebar .nav-link', false);
    if (alternate) {
      enableStylesheet(alternateStylesheets);
      for (const sheetNode of alternateStylesheets) {
        if (sheetNode.id === "quarto-bootstrap") {
          toggleBodyColorMode(sheetNode);
        }
      }
    } else {
      disableStylesheet(alternateStylesheets);
      toggleBodyColorPrimary();
    }
    manageTransitions('#quarto-margin-sidebar .nav-link', true);
    // Switch the toggles
    const toggles = window.document.querySelectorAll('.quarto-color-scheme-toggle');
    for (let i=0; i < toggles.length; i++) {
      const toggle = toggles[i];
      if (toggle) {
        if (alternate) {
          toggle.classList.add("alternate");     
        } else {
          toggle.classList.remove("alternate");
        }
      }
    }
    // Hack to workaround the fact that safari doesn't
    // properly recolor the scrollbar when toggling (#1455)
    if (navigator.userAgent.indexOf('Safari') > 0 && navigator.userAgent.indexOf('Chrome') == -1) {
      manageTransitions("body", false);
      window.scrollTo(0, 1);
      setTimeout(() => {
        window.scrollTo(0, 0);
        manageTransitions("body", true);
      }, 40);  
    }
  }
  const isFileUrl = () => { 
    return window.location.protocol === 'file:';
  }
  const hasAlternateSentinel = () => {  
    let styleSentinel = getColorSchemeSentinel();
    if (styleSentinel !== null) {
      return styleSentinel === "alternate";
    } else {
      return false;
    }
  }
  const setStyleSentinel = (alternate) => {
    const value = alternate ? "alternate" : "default";
    if (!isFileUrl()) {
      window.localStorage.setItem("quarto-color-scheme", value);
    } else {
      localAlternateSentinel = value;
    }
  }
  const getColorSchemeSentinel = () => {
    if (!isFileUrl()) {
      const storageValue = window.localStorage.getItem("quarto-color-scheme");
      return storageValue != null ? storageValue : localAlternateSentinel;
    } else {
      return localAlternateSentinel;
    }
  }
  const darkModeDefault = false;
  let localAlternateSentinel = darkModeDefault ? 'alternate' : 'default';
  // Dark / light mode switch
  window.quartoToggleColorScheme = () => {
    // Read the current dark / light value 
    let toAlternate = !hasAlternateSentinel();
    toggleColorMode(toAlternate);
    setStyleSentinel(toAlternate);
    toggleGiscusIfUsed(toAlternate, darkModeDefault);
  };
  // Ensure there is a toggle, if there isn't float one in the top right
  if (window.document.querySelector('.quarto-color-scheme-toggle') === null) {
    const a = window.document.createElement('a');
    a.classList.add('top-right');
    a.classList.add('quarto-color-scheme-toggle');
    a.href = "";
    a.onclick = function() { try { window.quartoToggleColorScheme(); } catch {} return false; };
    const i = window.document.createElement("i");
    i.classList.add('bi');
    a.appendChild(i);
    window.document.body.appendChild(a);
  }
  // Switch to dark mode if need be
  if (hasAlternateSentinel()) {
    toggleColorMode(true);
  } else {
    toggleColorMode(false);
  }
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    // For code content inside modals, clipBoardJS needs to be initialized with a container option
    // TODO: Check when it could be a function (https://github.com/zenorocha/clipboard.js/issues/860)
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
  const viewSource = window.document.getElementById('quarto-view-source') ||
                     window.document.getElementById('quarto-code-tools-source');
  if (viewSource) {
    const sourceUrl = viewSource.getAttribute("data-quarto-source-url");
    viewSource.addEventListener("click", function(e) {
      if (sourceUrl) {
        // rstudio viewer pane
        if (/\bcapabilities=\b/.test(window.location)) {
          window.open(sourceUrl);
        } else {
          window.location.href = sourceUrl;
        }
      } else {
        const modal = new bootstrap.Modal(document.getElementById('quarto-embedded-source-code-modal'));
        modal.show();
      }
      return false;
    });
  }
  function toggleCodeHandler(show) {
    return function(e) {
      const detailsSrc = window.document.querySelectorAll(".cell > details > .sourceCode");
      for (let i=0; i<detailsSrc.length; i++) {
        const details = detailsSrc[i].parentElement;
        if (show) {
          details.open = true;
        } else {
          details.removeAttribute("open");
        }
      }
      const cellCodeDivs = window.document.querySelectorAll(".cell > .sourceCode");
      const fromCls = show ? "hidden" : "unhidden";
      const toCls = show ? "unhidden" : "hidden";
      for (let i=0; i<cellCodeDivs.length; i++) {
        const codeDiv = cellCodeDivs[i];
        if (codeDiv.classList.contains(fromCls)) {
          codeDiv.classList.remove(fromCls);
          codeDiv.classList.add(toCls);
        } 
      }
      return false;
    }
  }
  const hideAllCode = window.document.getElementById("quarto-hide-all-code");
  if (hideAllCode) {
    hideAllCode.addEventListener("click", toggleCodeHandler(false));
  }
  const showAllCode = window.document.getElementById("quarto-show-all-code");
  if (showAllCode) {
    showAllCode.addEventListener("click", toggleCodeHandler(true));
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
          // target, if specified
          link.setAttribute("target", "_blank");
          if (link.getAttribute("rel") === null) {
            link.setAttribute("rel", "noopener");
          }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      // TODO in 1.5, we should make sure this works without a callout special case
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script><nav class="page-navigation column-body"><div class="nav-page nav-page-previous">
      <a href="../src/EDA - Phoebe Pan.html" class="pagination-link" aria-label="Phoebe P">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Phoebe P</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="../src/appx/effective teamwork - Zhijun.html" class="pagination-link" aria-label="Zhijun H">
        <span class="nav-page-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Zhijun H</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav><div class="modal fade" id="quarto-embedded-source-code-modal" tabindex="-1" aria-labelledby="quarto-embedded-source-code-modal-label" aria-hidden="true"><div class="modal-dialog modal-dialog-scrollable"><div class="modal-content"><div class="modal-header"><h5 class="modal-title" id="quarto-embedded-source-code-modal-label">Source Code</h5><button class="btn-close" data-bs-dismiss="modal"></button></div><div class="modal-body"><div class="">
<div class="sourceCode" id="cb11" data-shortcodes="false"><pre class="sourceCode numberSource markdown number-lines code-with-copy"><code class="sourceCode markdown"><span id="cb11-1"><a href="#cb11-1"></a><span class="co">---</span></span>
<span id="cb11-2"><a href="#cb11-2"></a><span class="an">title:</span><span class="co"> "Zhijun H"</span></span>
<span id="cb11-3"><a href="#cb11-3"></a><span class="an">number-sections:</span><span class="co"> true</span></span>
<span id="cb11-4"><a href="#cb11-4"></a><span class="an">code-fold:</span><span class="co"> true</span></span>
<span id="cb11-5"><a href="#cb11-5"></a><span class="an">execute:</span></span>
<span id="cb11-6"><a href="#cb11-6"></a><span class="co">  echo: true</span></span>
<span id="cb11-7"><a href="#cb11-7"></a><span class="co">---</span></span>
<span id="cb11-8"><a href="#cb11-8"></a><span class="fu">## Data Import and Preparation</span></span>
<span id="cb11-9"><a href="#cb11-9"></a></span>
<span id="cb11-10"><a href="#cb11-10"></a>In this analysis, I'm examining the historical performance and volatility patterns of six major global stock indices across different market cycles. The selection of indices provides a balanced geographic representation covering North America, Europe, and Asia, allowing for comprehensive cross-market comparison.</span>
<span id="cb11-11"><a href="#cb11-11"></a></span>
<span id="cb11-12"><a href="#cb11-12"></a><span class="in">```{r data_import, message=FALSE, warning=FALSE, results='hide'}</span></span>
<span id="cb11-13"><a href="#cb11-13"></a><span class="in"># Load required packages</span></span>
<span id="cb11-14"><a href="#cb11-14"></a><span class="in">library(tidyverse)</span></span>
<span id="cb11-15"><a href="#cb11-15"></a><span class="in">library(tidyquant)</span></span>
<span id="cb11-16"><a href="#cb11-16"></a><span class="in">library(lubridate)</span></span>
<span id="cb11-17"><a href="#cb11-17"></a><span class="in">library(TTR)</span></span>
<span id="cb11-18"><a href="#cb11-18"></a><span class="in">library(zoo)</span></span>
<span id="cb11-19"><a href="#cb11-19"></a><span class="in">library(gtsummary)</span></span>
<span id="cb11-20"><a href="#cb11-20"></a><span class="in">library(janitor)</span></span>
<span id="cb11-21"><a href="#cb11-21"></a><span class="in">library(visdat)</span></span>
<span id="cb11-22"><a href="#cb11-22"></a></span>
<span id="cb11-23"><a href="#cb11-23"></a><span class="in"># Define global market indices</span></span>
<span id="cb11-24"><a href="#cb11-24"></a><span class="in">indices &lt;- c(</span></span>
<span id="cb11-25"><a href="#cb11-25"></a><span class="in">  "^GSPC" = "S&amp;P 500",      # USA</span></span>
<span id="cb11-26"><a href="#cb11-26"></a><span class="in">  "^FTSE" = "FTSE 100",     # UK  </span></span>
<span id="cb11-27"><a href="#cb11-27"></a><span class="in">  "^N225" = "Nikkei 225",   # Japan</span></span>
<span id="cb11-28"><a href="#cb11-28"></a><span class="in">  "^GDAXI" = "DAX",         # Germany</span></span>
<span id="cb11-29"><a href="#cb11-29"></a><span class="in">  "^FCHI" = "CAC 40",       # France</span></span>
<span id="cb11-30"><a href="#cb11-30"></a><span class="in">  "^HSI" = "Hang Seng"      # Hong Kong</span></span>
<span id="cb11-31"><a href="#cb11-31"></a><span class="in">)</span></span>
<span id="cb11-32"><a href="#cb11-32"></a></span>
<span id="cb11-33"><a href="#cb11-33"></a><span class="in"># Import historical market data</span></span>
<span id="cb11-34"><a href="#cb11-34"></a><span class="in">market_data &lt;- tq_get(</span></span>
<span id="cb11-35"><a href="#cb11-35"></a><span class="in">  names(indices),</span></span>
<span id="cb11-36"><a href="#cb11-36"></a><span class="in">  get = "stock.prices",</span></span>
<span id="cb11-37"><a href="#cb11-37"></a><span class="in">  from = "2000-01-01",</span></span>
<span id="cb11-38"><a href="#cb11-38"></a><span class="in">  to = Sys.Date()</span></span>
<span id="cb11-39"><a href="#cb11-39"></a><span class="in">) %&gt;%</span></span>
<span id="cb11-40"><a href="#cb11-40"></a><span class="in">  # Add descriptive names for better readability</span></span>
<span id="cb11-41"><a href="#cb11-41"></a><span class="in">  mutate(index_name = indices[symbol])</span></span>
<span id="cb11-42"><a href="#cb11-42"></a><span class="in">```</span></span>
<span id="cb11-43"><a href="#cb11-43"></a></span>
<span id="cb11-44"><a href="#cb11-44"></a><span class="in">```{r summary_output, echo=FALSE, results='asis'}</span></span>
<span id="cb11-45"><a href="#cb11-45"></a><span class="in"># Create formatted output using direct HTML to avoid package warnings</span></span>
<span id="cb11-46"><a href="#cb11-46"></a><span class="in">cat('</span></span>
<span id="cb11-47"><a href="#cb11-47"></a><span class="in">&lt;div style="margin: 20px 0; padding: 15px; border-radius: 5px; background-color: #f8f9fa; border: 1px solid #dee2e6;"&gt;</span></span>
<span id="cb11-48"><a href="#cb11-48"></a><span class="in">  &lt;h3 style="margin-top: 0; color: #495057;"&gt;Data Import Summary&lt;/h3&gt;</span></span>
<span id="cb11-49"><a href="#cb11-49"></a><span class="in">  </span></span>
<span id="cb11-50"><a href="#cb11-50"></a><span class="in">  &lt;table style="width: 100%; border-collapse: collapse;"&gt;</span></span>
<span id="cb11-51"><a href="#cb11-51"></a><span class="in">    &lt;tr&gt;</span></span>
<span id="cb11-52"><a href="#cb11-52"></a><span class="in">      &lt;td style="padding: 8px; font-weight: bold; width: 30%;"&gt;Dataset Size:&lt;/td&gt;</span></span>
<span id="cb11-53"><a href="#cb11-53"></a><span class="in">      &lt;td style="padding: 8px;"&gt;', format(nrow(market_data), big.mark=","), ' observations&lt;/td&gt;</span></span>
<span id="cb11-54"><a href="#cb11-54"></a><span class="in">    &lt;/tr&gt;</span></span>
<span id="cb11-55"><a href="#cb11-55"></a><span class="in">    &lt;tr&gt;</span></span>
<span id="cb11-56"><a href="#cb11-56"></a><span class="in">      &lt;td style="padding: 8px; font-weight: bold; border-top: 1px solid #dee2e6;"&gt;Time Period:&lt;/td&gt;</span></span>
<span id="cb11-57"><a href="#cb11-57"></a><span class="in">      &lt;td style="padding: 8px; border-top: 1px solid #dee2e6;"&gt;', </span></span>
<span id="cb11-58"><a href="#cb11-58"></a><span class="in">        format(min(market_data$date, na.rm=TRUE), "%b %d, %Y"), ' to ', </span></span>
<span id="cb11-59"><a href="#cb11-59"></a><span class="in">        format(max(market_data$date, na.rm=TRUE), "%b %d, %Y"), </span></span>
<span id="cb11-60"><a href="#cb11-60"></a><span class="in">      '&lt;/td&gt;</span></span>
<span id="cb11-61"><a href="#cb11-61"></a><span class="in">    &lt;/tr&gt;</span></span>
<span id="cb11-62"><a href="#cb11-62"></a><span class="in">    &lt;tr&gt;</span></span>
<span id="cb11-63"><a href="#cb11-63"></a><span class="in">      &lt;td style="padding: 8px; font-weight: bold; border-top: 1px solid #dee2e6;"&gt;Market Coverage:&lt;/td&gt;</span></span>
<span id="cb11-64"><a href="#cb11-64"></a><span class="in">      &lt;td style="padding: 8px; border-top: 1px solid #dee2e6;"&gt;6 global indices&lt;/td&gt;</span></span>
<span id="cb11-65"><a href="#cb11-65"></a><span class="in">    &lt;/tr&gt;</span></span>
<span id="cb11-66"><a href="#cb11-66"></a><span class="in">  &lt;/table&gt;</span></span>
<span id="cb11-67"><a href="#cb11-67"></a><span class="in">  </span></span>
<span id="cb11-68"><a href="#cb11-68"></a><span class="in">  &lt;h4 style="margin-top: 20px; color: #495057;"&gt;Geographic Distribution&lt;/h4&gt;</span></span>
<span id="cb11-69"><a href="#cb11-69"></a><span class="in">  </span></span>
<span id="cb11-70"><a href="#cb11-70"></a><span class="in">  &lt;table style="width: 100%; border-collapse: collapse; margin-bottom: 10px;"&gt;</span></span>
<span id="cb11-71"><a href="#cb11-71"></a><span class="in">    &lt;tr&gt;</span></span>
<span id="cb11-72"><a href="#cb11-72"></a><span class="in">      &lt;th style="text-align: left; padding: 8px; background-color: #e9ecef; width: 30%;"&gt;Region&lt;/th&gt;</span></span>
<span id="cb11-73"><a href="#cb11-73"></a><span class="in">      &lt;th style="text-align: left; padding: 8px; background-color: #e9ecef;"&gt;Indices&lt;/th&gt;</span></span>
<span id="cb11-74"><a href="#cb11-74"></a><span class="in">    &lt;/tr&gt;</span></span>
<span id="cb11-75"><a href="#cb11-75"></a><span class="in">    &lt;tr&gt;</span></span>
<span id="cb11-76"><a href="#cb11-76"></a><span class="in">      &lt;td style="padding: 8px; font-weight: bold;"&gt;North America&lt;/td&gt;</span></span>
<span id="cb11-77"><a href="#cb11-77"></a><span class="in">      &lt;td style="padding: 8px;"&gt;S&amp;P 500 (United States)&lt;/td&gt;</span></span>
<span id="cb11-78"><a href="#cb11-78"></a><span class="in">    &lt;/tr&gt;</span></span>
<span id="cb11-79"><a href="#cb11-79"></a><span class="in">    &lt;tr&gt;</span></span>
<span id="cb11-80"><a href="#cb11-80"></a><span class="in">      &lt;td style="padding: 8px; font-weight: bold; background-color: #f2f2f2;"&gt;Europe&lt;/td&gt;</span></span>
<span id="cb11-81"><a href="#cb11-81"></a><span class="in">      &lt;td style="padding: 8px; background-color: #f2f2f2;"&gt;FTSE 100 (UK), DAX (Germany), CAC 40 (France)&lt;/td&gt;</span></span>
<span id="cb11-82"><a href="#cb11-82"></a><span class="in">    &lt;/tr&gt;</span></span>
<span id="cb11-83"><a href="#cb11-83"></a><span class="in">    &lt;tr&gt;</span></span>
<span id="cb11-84"><a href="#cb11-84"></a><span class="in">      &lt;td style="padding: 8px; font-weight: bold;"&gt;Asia&lt;/td&gt;</span></span>
<span id="cb11-85"><a href="#cb11-85"></a><span class="in">      &lt;td style="padding: 8px;"&gt;Nikkei 225 (Japan), Hang Seng (Hong Kong)&lt;/td&gt;</span></span>
<span id="cb11-86"><a href="#cb11-86"></a><span class="in">    &lt;/tr&gt;</span></span>
<span id="cb11-87"><a href="#cb11-87"></a><span class="in">  &lt;/table&gt;</span></span>
<span id="cb11-88"><a href="#cb11-88"></a><span class="in">&lt;/div&gt;</span></span>
<span id="cb11-89"><a href="#cb11-89"></a><span class="in">')</span></span>
<span id="cb11-90"><a href="#cb11-90"></a><span class="in">```</span></span>
<span id="cb11-91"><a href="#cb11-91"></a></span>
<span id="cb11-92"><a href="#cb11-92"></a>The data collection process leverages the tidyquant package's integration with Yahoo Finance to retrieve daily trading information for each index from January 2000 through May 2025. This extensive timeframe encompasses multiple economic cycles, bull and bear markets, and several major financial crises, providing a robust foundation for volatility analysis. For each index, I capture standard OHLC (Open, High, Low, Close) price data along with trading volume and adjusted prices that account for dividends and splits.</span>
<span id="cb11-93"><a href="#cb11-93"></a></span>
<span id="cb11-94"><a href="#cb11-94"></a><span class="fu">## Data Structure and Quality Assessment</span></span>
<span id="cb11-95"><a href="#cb11-95"></a></span>
<span id="cb11-96"><a href="#cb11-96"></a><span class="in">```{r dataset_overview, message=FALSE, warning=FALSE, echo=FALSE, results='asis'}</span></span>
<span id="cb11-97"><a href="#cb11-97"></a><span class="in"># Create a boxed summary for dataset overview</span></span>
<span id="cb11-98"><a href="#cb11-98"></a><span class="in">cat('&lt;div class="dataset-overview" style="background-color: #f8f9fa; padding: 15px; border-radius: 5px; margin-bottom: 20px; border-left: 5px solid #4682B4;"&gt;')</span></span>
<span id="cb11-99"><a href="#cb11-99"></a><span class="in">cat('&lt;h3 style="margin-top: 0;"&gt;Dataset Overview&lt;/h3&gt;\n\n')</span></span>
<span id="cb11-100"><a href="#cb11-100"></a></span>
<span id="cb11-101"><a href="#cb11-101"></a><span class="in"># Create a clean summary table</span></span>
<span id="cb11-102"><a href="#cb11-102"></a><span class="in">overview_data &lt;- data.frame(</span></span>
<span id="cb11-103"><a href="#cb11-103"></a><span class="in">  Metric = c("Observations", "Date Range", "Market Indices"),</span></span>
<span id="cb11-104"><a href="#cb11-104"></a><span class="in">  Value = c(</span></span>
<span id="cb11-105"><a href="#cb11-105"></a><span class="in">    format(nrow(market_data), big.mark=","),</span></span>
<span id="cb11-106"><a href="#cb11-106"></a><span class="in">    paste0(format(min(market_data$date), "%B %d, %Y"), " to ", format(max(market_data$date), "%B %d, %Y")),</span></span>
<span id="cb11-107"><a href="#cb11-107"></a><span class="in">    length(unique(market_data$symbol))</span></span>
<span id="cb11-108"><a href="#cb11-108"></a><span class="in">  )</span></span>
<span id="cb11-109"><a href="#cb11-109"></a><span class="in">)</span></span>
<span id="cb11-110"><a href="#cb11-110"></a></span>
<span id="cb11-111"><a href="#cb11-111"></a><span class="in"># Create a simple HTML table</span></span>
<span id="cb11-112"><a href="#cb11-112"></a><span class="in">cat('&lt;table style="width: auto; margin-bottom: 15px;"&gt;')</span></span>
<span id="cb11-113"><a href="#cb11-113"></a><span class="in">for (i in 1:nrow(overview_data)) {</span></span>
<span id="cb11-114"><a href="#cb11-114"></a><span class="in">  cat('&lt;tr&gt;')</span></span>
<span id="cb11-115"><a href="#cb11-115"></a><span class="in">  cat(paste0('&lt;td style="padding-right: 20px; font-weight: bold;"&gt;', overview_data$Metric[i], ':&lt;/td&gt;'))</span></span>
<span id="cb11-116"><a href="#cb11-116"></a><span class="in">  cat(paste0('&lt;td&gt;', overview_data$Value[i], '&lt;/td&gt;'))</span></span>
<span id="cb11-117"><a href="#cb11-117"></a><span class="in">  cat('&lt;/tr&gt;')</span></span>
<span id="cb11-118"><a href="#cb11-118"></a><span class="in">}</span></span>
<span id="cb11-119"><a href="#cb11-119"></a><span class="in">cat('&lt;/table&gt;')</span></span>
<span id="cb11-120"><a href="#cb11-120"></a><span class="in">cat('&lt;/div&gt;')</span></span>
<span id="cb11-121"><a href="#cb11-121"></a><span class="in">```</span></span>
<span id="cb11-122"><a href="#cb11-122"></a></span>
<span id="cb11-123"><a href="#cb11-123"></a><span class="in">```{r missing_values_viz, message=FALSE, warning=FALSE, fig.height=5, fig.width=9}</span></span>
<span id="cb11-124"><a href="#cb11-124"></a><span class="in"># Create more informative missing values visualization with improved styling</span></span>
<span id="cb11-125"><a href="#cb11-125"></a><span class="in">vis_miss(market_data) +</span></span>
<span id="cb11-126"><a href="#cb11-126"></a><span class="in">  labs(</span></span>
<span id="cb11-127"><a href="#cb11-127"></a><span class="in">    title = "Missing Values Distribution in Market Dataset",</span></span>
<span id="cb11-128"><a href="#cb11-128"></a><span class="in">    subtitle = "White areas represent available data, black indicates missing values",</span></span>
<span id="cb11-129"><a href="#cb11-129"></a><span class="in">    caption = "Source: Yahoo Finance data retrieved via tidyquant package, Analysis by Zhijun H, May 2025"</span></span>
<span id="cb11-130"><a href="#cb11-130"></a><span class="in">  ) +</span></span>
<span id="cb11-131"><a href="#cb11-131"></a><span class="in">  theme_minimal() +</span></span>
<span id="cb11-132"><a href="#cb11-132"></a><span class="in">  theme(</span></span>
<span id="cb11-133"><a href="#cb11-133"></a><span class="in">    plot.title = element_text(face = "bold", size = 14),</span></span>
<span id="cb11-134"><a href="#cb11-134"></a><span class="in">    plot.subtitle = element_text(size = 11, color = "gray30"),</span></span>
<span id="cb11-135"><a href="#cb11-135"></a><span class="in">    axis.text.x = element_text(angle = 45, hjust = 1),</span></span>
<span id="cb11-136"><a href="#cb11-136"></a><span class="in">    plot.caption = element_text(color = "gray50", size = 9),</span></span>
<span id="cb11-137"><a href="#cb11-137"></a><span class="in">    panel.grid.minor = element_blank()</span></span>
<span id="cb11-138"><a href="#cb11-138"></a><span class="in">  )</span></span>
<span id="cb11-139"><a href="#cb11-139"></a><span class="in">```</span></span>
<span id="cb11-140"><a href="#cb11-140"></a></span>
<span id="cb11-141"><a href="#cb11-141"></a><span class="in">```{r completeness_analysis, message=FALSE, warning=FALSE, echo=FALSE}</span></span>
<span id="cb11-142"><a href="#cb11-142"></a><span class="in"># Calculate completeness metrics</span></span>
<span id="cb11-143"><a href="#cb11-143"></a><span class="in">completeness_by_index &lt;- market_data %&gt;%</span></span>
<span id="cb11-144"><a href="#cb11-144"></a><span class="in">  group_by(index_name) %&gt;%</span></span>
<span id="cb11-145"><a href="#cb11-145"></a><span class="in">  summarize(</span></span>
<span id="cb11-146"><a href="#cb11-146"></a><span class="in">    start_date = min(date),</span></span>
<span id="cb11-147"><a href="#cb11-147"></a><span class="in">    end_date = max(date),</span></span>
<span id="cb11-148"><a href="#cb11-148"></a><span class="in">    expected_days = as.numeric(difftime(max(date), min(date), units = "days")),</span></span>
<span id="cb11-149"><a href="#cb11-149"></a><span class="in">    actual_records = n(),</span></span>
<span id="cb11-150"><a href="#cb11-150"></a><span class="in">    completeness_ratio = actual_records / expected_days,</span></span>
<span id="cb11-151"><a href="#cb11-151"></a><span class="in">    completeness_percent = round(completeness_ratio * 100, 1),</span></span>
<span id="cb11-152"><a href="#cb11-152"></a><span class="in">    .groups = "drop"</span></span>
<span id="cb11-153"><a href="#cb11-153"></a><span class="in">  )</span></span>
<span id="cb11-154"><a href="#cb11-154"></a><span class="in">```</span></span>
<span id="cb11-155"><a href="#cb11-155"></a></span>
<span id="cb11-156"><a href="#cb11-156"></a><span class="in">```{r completeness_chart, message=FALSE, warning=FALSE, fig.height=5, fig.width=9}</span></span>
<span id="cb11-157"><a href="#cb11-157"></a><span class="in"># Create visually enhanced completeness chart</span></span>
<span id="cb11-158"><a href="#cb11-158"></a><span class="in">ggplot(completeness_by_index, </span></span>
<span id="cb11-159"><a href="#cb11-159"></a><span class="in">       aes(x = reorder(index_name, completeness_percent), y = completeness_percent, fill = index_name)) +</span></span>
<span id="cb11-160"><a href="#cb11-160"></a><span class="in">  geom_col(width = 0.7, alpha = 0.9) +</span></span>
<span id="cb11-161"><a href="#cb11-161"></a><span class="in">  geom_text(</span></span>
<span id="cb11-162"><a href="#cb11-162"></a><span class="in">    aes(label = paste0(completeness_percent, "%")),</span></span>
<span id="cb11-163"><a href="#cb11-163"></a><span class="in">    vjust = -0.5, </span></span>
<span id="cb11-164"><a href="#cb11-164"></a><span class="in">    color = "gray30", </span></span>
<span id="cb11-165"><a href="#cb11-165"></a><span class="in">    size = 3.8,</span></span>
<span id="cb11-166"><a href="#cb11-166"></a><span class="in">    fontface = "bold"</span></span>
<span id="cb11-167"><a href="#cb11-167"></a><span class="in">  ) +</span></span>
<span id="cb11-168"><a href="#cb11-168"></a><span class="in">  labs(</span></span>
<span id="cb11-169"><a href="#cb11-169"></a><span class="in">    title = "Data Completeness by Global Market Index",</span></span>
<span id="cb11-170"><a href="#cb11-170"></a><span class="in">    subtitle = "Percentage of calendar days with available trading data from 2000-2025",</span></span>
<span id="cb11-171"><a href="#cb11-171"></a><span class="in">    x = NULL,</span></span>
<span id="cb11-172"><a href="#cb11-172"></a><span class="in">    y = "Completeness (%)",</span></span>
<span id="cb11-173"><a href="#cb11-173"></a><span class="in">    caption = "Source: Yahoo Finance data retrieved via tidyquant package, Analysis by Zhijun H, May 2025"</span></span>
<span id="cb11-174"><a href="#cb11-174"></a><span class="in">  ) +</span></span>
<span id="cb11-175"><a href="#cb11-175"></a><span class="in">  scale_y_continuous(</span></span>
<span id="cb11-176"><a href="#cb11-176"></a><span class="in">    limits = c(0, 100),</span></span>
<span id="cb11-177"><a href="#cb11-177"></a><span class="in">    breaks = seq(0, 100, by = 20),</span></span>
<span id="cb11-178"><a href="#cb11-178"></a><span class="in">    labels = function(x) paste0(x, "%")</span></span>
<span id="cb11-179"><a href="#cb11-179"></a><span class="in">  ) +</span></span>
<span id="cb11-180"><a href="#cb11-180"></a><span class="in">  scale_fill_brewer(palette = "Set2") +</span></span>
<span id="cb11-181"><a href="#cb11-181"></a><span class="in">  theme_minimal() +</span></span>
<span id="cb11-182"><a href="#cb11-182"></a><span class="in">  theme(</span></span>
<span id="cb11-183"><a href="#cb11-183"></a><span class="in">    legend.position = "none",</span></span>
<span id="cb11-184"><a href="#cb11-184"></a><span class="in">    plot.title = element_text(face = "bold", size = 14),</span></span>
<span id="cb11-185"><a href="#cb11-185"></a><span class="in">    plot.subtitle = element_text(size = 11, color = "gray30"),</span></span>
<span id="cb11-186"><a href="#cb11-186"></a><span class="in">    axis.text.x = element_text(angle = 45, hjust = 1, face = "bold"),</span></span>
<span id="cb11-187"><a href="#cb11-187"></a><span class="in">    axis.text.y = element_text(face = "bold"),</span></span>
<span id="cb11-188"><a href="#cb11-188"></a><span class="in">    plot.caption = element_text(color = "gray50", size = 9),</span></span>
<span id="cb11-189"><a href="#cb11-189"></a><span class="in">    panel.grid.minor = element_blank()</span></span>
<span id="cb11-190"><a href="#cb11-190"></a><span class="in">  )</span></span>
<span id="cb11-191"><a href="#cb11-191"></a><span class="in">```</span></span>
<span id="cb11-192"><a href="#cb11-192"></a></span>
<span id="cb11-193"><a href="#cb11-193"></a><span class="in">```{r completeness_table, message=FALSE, warning=FALSE, echo=FALSE}</span></span>
<span id="cb11-194"><a href="#cb11-194"></a><span class="in"># Display completeness table with improved formatting using kableExtra</span></span>
<span id="cb11-195"><a href="#cb11-195"></a><span class="in">completeness_by_index %&gt;%</span></span>
<span id="cb11-196"><a href="#cb11-196"></a><span class="in">  select(index_name, start_date, end_date, actual_records, completeness_percent) %&gt;%</span></span>
<span id="cb11-197"><a href="#cb11-197"></a><span class="in">  rename(</span></span>
<span id="cb11-198"><a href="#cb11-198"></a><span class="in">    "Index" = index_name,</span></span>
<span id="cb11-199"><a href="#cb11-199"></a><span class="in">    "Start Date" = start_date,</span></span>
<span id="cb11-200"><a href="#cb11-200"></a><span class="in">    "End Date" = end_date,</span></span>
<span id="cb11-201"><a href="#cb11-201"></a><span class="in">    "Trading Days" = actual_records,</span></span>
<span id="cb11-202"><a href="#cb11-202"></a><span class="in">    "Completeness (%)" = completeness_percent</span></span>
<span id="cb11-203"><a href="#cb11-203"></a><span class="in">  ) %&gt;%</span></span>
<span id="cb11-204"><a href="#cb11-204"></a><span class="in">  mutate(</span></span>
<span id="cb11-205"><a href="#cb11-205"></a><span class="in">    "Start Date" = format(`Start Date`, "%b %d, %Y"),</span></span>
<span id="cb11-206"><a href="#cb11-206"></a><span class="in">    "End Date" = format(`End Date`, "%b %d, %Y"),</span></span>
<span id="cb11-207"><a href="#cb11-207"></a><span class="in">    "Trading Days" = format(`Trading Days`, big.mark = ",")</span></span>
<span id="cb11-208"><a href="#cb11-208"></a><span class="in">  ) %&gt;%</span></span>
<span id="cb11-209"><a href="#cb11-209"></a><span class="in">  knitr::kable(</span></span>
<span id="cb11-210"><a href="#cb11-210"></a><span class="in">    format = "html",</span></span>
<span id="cb11-211"><a href="#cb11-211"></a><span class="in">    caption = "Data Completeness Metrics by Index",</span></span>
<span id="cb11-212"><a href="#cb11-212"></a><span class="in">    align = c("l", "c", "c", "r", "c"),</span></span>
<span id="cb11-213"><a href="#cb11-213"></a><span class="in">    digits = 1</span></span>
<span id="cb11-214"><a href="#cb11-214"></a><span class="in">  ) %&gt;%</span></span>
<span id="cb11-215"><a href="#cb11-215"></a><span class="in">  kableExtra::kable_styling(</span></span>
<span id="cb11-216"><a href="#cb11-216"></a><span class="in">    bootstrap_options = c("striped", "hover", "condensed"),</span></span>
<span id="cb11-217"><a href="#cb11-217"></a><span class="in">    full_width = FALSE,</span></span>
<span id="cb11-218"><a href="#cb11-218"></a><span class="in">    position = "center"</span></span>
<span id="cb11-219"><a href="#cb11-219"></a><span class="in">  ) %&gt;%</span></span>
<span id="cb11-220"><a href="#cb11-220"></a><span class="in">  kableExtra::row_spec(0, bold = TRUE, background = "#f5f5f5") %&gt;%</span></span>
<span id="cb11-221"><a href="#cb11-221"></a><span class="in">  kableExtra::column_spec(1, bold = TRUE) %&gt;%</span></span>
<span id="cb11-222"><a href="#cb11-222"></a><span class="in">  kableExtra::column_spec(5, bold = TRUE, color = "white", </span></span>
<span id="cb11-223"><a href="#cb11-223"></a><span class="in">                        background = case_when(</span></span>
<span id="cb11-224"><a href="#cb11-224"></a><span class="in">                          completeness_by_index$completeness_percent &gt;= 70 ~ "#28a745",</span></span>
<span id="cb11-225"><a href="#cb11-225"></a><span class="in">                          completeness_by_index$completeness_percent &gt;= 65 ~ "#ffc107",</span></span>
<span id="cb11-226"><a href="#cb11-226"></a><span class="in">                          TRUE ~ "#dc3545"</span></span>
<span id="cb11-227"><a href="#cb11-227"></a><span class="in">                        ))</span></span>
<span id="cb11-228"><a href="#cb11-228"></a><span class="in">```</span></span>
<span id="cb11-229"><a href="#cb11-229"></a></span>
<span id="cb11-230"><a href="#cb11-230"></a>The dataset consists of nearly 38,500 daily observations across six major global indices spanning over 25 years. The completeness analysis reveals consistent data availability across all markets, with completeness ratios between 68-70%. This pattern aligns with expectations given that trading doesn't occur on weekends and holidays, which typically account for approximately 30% of calendar days annually. </span>
<span id="cb11-231"><a href="#cb11-231"></a></span>
<span id="cb11-232"><a href="#cb11-232"></a>European indices (FTSE 100, DAX, and CAC 40) show slightly higher completeness rates, potentially reflecting fewer market holidays compared to Asian exchanges. The Hang Seng index exhibits the lowest completeness at 68.3%, which can be attributed to extended New Year celebrations and additional regional holidays observed in Hong Kong. These small variations in data availability don't significantly impact our analysis, as each index still provides robust coverage across the entire study period.</span>
<span id="cb11-233"><a href="#cb11-233"></a></span>
<span id="cb11-234"><a href="#cb11-234"></a>This thorough assessment confirms we have a high-quality dataset with consistent trading information across different market environments, providing a solid foundation for examining volatility patterns through multiple economic cycles and global events.</span>
<span id="cb11-235"><a href="#cb11-235"></a></span>
<span id="cb11-236"><a href="#cb11-236"></a><span class="fu">## Price Trends and Market Evolution</span></span>
<span id="cb11-237"><a href="#cb11-237"></a></span>
<span id="cb11-238"><a href="#cb11-238"></a><span class="in">```{r price_trends, fig.width=10, fig.height=6, message=FALSE, warning=FALSE}</span></span>
<span id="cb11-239"><a href="#cb11-239"></a><span class="in"># Visualizing long-term price trends with annotations for major events</span></span>
<span id="cb11-240"><a href="#cb11-240"></a><span class="in">financial_events &lt;- data.frame(</span></span>
<span id="cb11-241"><a href="#cb11-241"></a><span class="in">  date = as.Date(c("2008-09-15", "2020-03-11", "2022-02-24")),</span></span>
<span id="cb11-242"><a href="#cb11-242"></a><span class="in">  event = c("2008 Financial Crisis", "COVID-19 Pandemic", "Russia-Ukraine Conflict"),</span></span>
<span id="cb11-243"><a href="#cb11-243"></a><span class="in">  y_position = c(20000, 25000, 30000)</span></span>
<span id="cb11-244"><a href="#cb11-244"></a><span class="in">)</span></span>
<span id="cb11-245"><a href="#cb11-245"></a></span>
<span id="cb11-246"><a href="#cb11-246"></a><span class="in">ggplot() +</span></span>
<span id="cb11-247"><a href="#cb11-247"></a><span class="in">  geom_line(data = market_data, </span></span>
<span id="cb11-248"><a href="#cb11-248"></a><span class="in">            aes(x = date, y = adjusted, color = index_name),</span></span>
<span id="cb11-249"><a href="#cb11-249"></a><span class="in">            linewidth = 0.7, alpha = 0.8) +</span></span>
<span id="cb11-250"><a href="#cb11-250"></a><span class="in">  geom_vline(data = financial_events, </span></span>
<span id="cb11-251"><a href="#cb11-251"></a><span class="in">             aes(xintercept = date),</span></span>
<span id="cb11-252"><a href="#cb11-252"></a><span class="in">             linetype = "dashed", alpha = 0.7) +</span></span>
<span id="cb11-253"><a href="#cb11-253"></a><span class="in">  geom_text(data = financial_events,</span></span>
<span id="cb11-254"><a href="#cb11-254"></a><span class="in">            aes(x = date, y = y_position, label = event),</span></span>
<span id="cb11-255"><a href="#cb11-255"></a><span class="in">            hjust = -0.1, vjust = 0, size = 3, angle = 90) +</span></span>
<span id="cb11-256"><a href="#cb11-256"></a><span class="in">  labs(</span></span>
<span id="cb11-257"><a href="#cb11-257"></a><span class="in">    title = "The Resilient Rise: Market Price Evolution Across Major Indices (2000-2025)",</span></span>
<span id="cb11-258"><a href="#cb11-258"></a><span class="in">    subtitle = "Tracing growth trajectories through financial crises and recoveries",</span></span>
<span id="cb11-259"><a href="#cb11-259"></a><span class="in">    x = "Year",</span></span>
<span id="cb11-260"><a href="#cb11-260"></a><span class="in">    y = "Adjusted Closing Price",</span></span>
<span id="cb11-261"><a href="#cb11-261"></a><span class="in">    color = "Index",</span></span>
<span id="cb11-262"><a href="#cb11-262"></a><span class="in">    caption = "Source: Yahoo Finance data retrieved via tidyquant package, Analysis by Zhijun H, May 2025"</span></span>
<span id="cb11-263"><a href="#cb11-263"></a><span class="in">  ) +</span></span>
<span id="cb11-264"><a href="#cb11-264"></a><span class="in">  scale_x_date(date_breaks = "2 years", date_labels = "%Y") +</span></span>
<span id="cb11-265"><a href="#cb11-265"></a><span class="in">  scale_y_continuous(labels = scales::comma) +</span></span>
<span id="cb11-266"><a href="#cb11-266"></a><span class="in">  theme_minimal() +</span></span>
<span id="cb11-267"><a href="#cb11-267"></a><span class="in">  theme(</span></span>
<span id="cb11-268"><a href="#cb11-268"></a><span class="in">    legend.position = "bottom",</span></span>
<span id="cb11-269"><a href="#cb11-269"></a><span class="in">    plot.title = element_text(face = "bold"),</span></span>
<span id="cb11-270"><a href="#cb11-270"></a><span class="in">    panel.grid.minor = element_blank()</span></span>
<span id="cb11-271"><a href="#cb11-271"></a><span class="in">  )</span></span>
<span id="cb11-272"><a href="#cb11-272"></a><span class="in">```</span></span>
<span id="cb11-273"><a href="#cb11-273"></a></span>
<span id="cb11-274"><a href="#cb11-274"></a>Examining the long-term price trends reveals a fascinating story of market resilience and regional divergence. Despite facing three major global crises over the past quarter-century, all indices have demonstrated remarkable recovery capabilities, though with distinct patterns. The S&amp;P 500 stands out with its exceptional post-crisis performance, particularly following the 2008 financial crisis and the 2020 pandemic, where its recovery trajectory significantly outpaced other major markets. European indices (DAX, CAC 40, FTSE 100) show more moderate but steady growth, while Asian markets exhibit greater volatility during crisis periods but also powerful recoveries, particularly the Nikkei 225 after 2012. These divergent recovery patterns highlight the influence of regional economic policies, sector compositions, and monetary interventions on market performance.</span>
<span id="cb11-275"><a href="#cb11-275"></a></span>
<span id="cb11-276"><a href="#cb11-276"></a><span class="fu">## Volatility Analysis: The Heartbeat of Markets</span></span>
<span id="cb11-277"><a href="#cb11-277"></a></span>
<span id="cb11-278"><a href="#cb11-278"></a><span class="in">```{r calculate_returns, message=FALSE, warning=FALSE}</span></span>
<span id="cb11-279"><a href="#cb11-279"></a><span class="in"># Calculating daily returns and volatility metrics</span></span>
<span id="cb11-280"><a href="#cb11-280"></a><span class="in">market_analysis &lt;- market_data %&gt;%</span></span>
<span id="cb11-281"><a href="#cb11-281"></a><span class="in">  group_by(symbol, index_name) %&gt;%</span></span>
<span id="cb11-282"><a href="#cb11-282"></a><span class="in">  arrange(date) %&gt;%</span></span>
<span id="cb11-283"><a href="#cb11-283"></a><span class="in">  # Computing daily percentage returns</span></span>
<span id="cb11-284"><a href="#cb11-284"></a><span class="in">  mutate(</span></span>
<span id="cb11-285"><a href="#cb11-285"></a><span class="in">    daily_return = (adjusted / lag(adjusted) - 1) * 100,</span></span>
<span id="cb11-286"><a href="#cb11-286"></a><span class="in">    # Adding multiple volatility measures</span></span>
<span id="cb11-287"><a href="#cb11-287"></a><span class="in">    rolling_vol_20 = rollapply(</span></span>
<span id="cb11-288"><a href="#cb11-288"></a><span class="in">      daily_return,</span></span>
<span id="cb11-289"><a href="#cb11-289"></a><span class="in">      width = 20,</span></span>
<span id="cb11-290"><a href="#cb11-290"></a><span class="in">      FUN = function(x) sd(x, na.rm = TRUE) * sqrt(252),</span></span>
<span id="cb11-291"><a href="#cb11-291"></a><span class="in">      align = "right",</span></span>
<span id="cb11-292"><a href="#cb11-292"></a><span class="in">      fill = NA</span></span>
<span id="cb11-293"><a href="#cb11-293"></a><span class="in">    ),</span></span>
<span id="cb11-294"><a href="#cb11-294"></a><span class="in">    rolling_vol_60 = rollapply(</span></span>
<span id="cb11-295"><a href="#cb11-295"></a><span class="in">      daily_return,</span></span>
<span id="cb11-296"><a href="#cb11-296"></a><span class="in">      width = 60,</span></span>
<span id="cb11-297"><a href="#cb11-297"></a><span class="in">      FUN = function(x) sd(x, na.rm = TRUE) * sqrt(252),</span></span>
<span id="cb11-298"><a href="#cb11-298"></a><span class="in">      align = "right",</span></span>
<span id="cb11-299"><a href="#cb11-299"></a><span class="in">      fill = NA</span></span>
<span id="cb11-300"><a href="#cb11-300"></a><span class="in">    ),</span></span>
<span id="cb11-301"><a href="#cb11-301"></a><span class="in">    # Adding year and month for temporal analysis</span></span>
<span id="cb11-302"><a href="#cb11-302"></a><span class="in">    year = lubridate::year(date),</span></span>
<span id="cb11-303"><a href="#cb11-303"></a><span class="in">    month_num = lubridate::month(date)</span></span>
<span id="cb11-304"><a href="#cb11-304"></a><span class="in">  ) %&gt;%</span></span>
<span id="cb11-305"><a href="#cb11-305"></a><span class="in">  ungroup() %&gt;%</span></span>
<span id="cb11-306"><a href="#cb11-306"></a><span class="in">  # Create month factor with labels</span></span>
<span id="cb11-307"><a href="#cb11-307"></a><span class="in">  mutate(month = factor(month_num, </span></span>
<span id="cb11-308"><a href="#cb11-308"></a><span class="in">                       levels = 1:12, </span></span>
<span id="cb11-309"><a href="#cb11-309"></a><span class="in">                       labels = c("Jan", "Feb", "Mar", "Apr", "May", "Jun", </span></span>
<span id="cb11-310"><a href="#cb11-310"></a><span class="in">                                  "Jul", "Aug", "Sep", "Oct", "Nov", "Dec")))</span></span>
<span id="cb11-311"><a href="#cb11-311"></a></span>
<span id="cb11-312"><a href="#cb11-312"></a><span class="in"># Using gtsummary for a comprehensive statistical summary</span></span>
<span id="cb11-313"><a href="#cb11-313"></a><span class="in">market_analysis %&gt;%</span></span>
<span id="cb11-314"><a href="#cb11-314"></a><span class="in">  select(index_name, daily_return, rolling_vol_20, rolling_vol_60) %&gt;%</span></span>
<span id="cb11-315"><a href="#cb11-315"></a><span class="in">  tbl_summary(</span></span>
<span id="cb11-316"><a href="#cb11-316"></a><span class="in">    by = index_name,</span></span>
<span id="cb11-317"><a href="#cb11-317"></a><span class="in">    statistic = list(</span></span>
<span id="cb11-318"><a href="#cb11-318"></a><span class="in">      all_continuous() ~ "{mean} ({sd})"</span></span>
<span id="cb11-319"><a href="#cb11-319"></a><span class="in">    ),</span></span>
<span id="cb11-320"><a href="#cb11-320"></a><span class="in">    digits = all_continuous() ~ 2</span></span>
<span id="cb11-321"><a href="#cb11-321"></a><span class="in">  ) %&gt;%</span></span>
<span id="cb11-322"><a href="#cb11-322"></a><span class="in">  add_stat_label() %&gt;%</span></span>
<span id="cb11-323"><a href="#cb11-323"></a><span class="in">  modify_header(label = "**Metric**") %&gt;%</span></span>
<span id="cb11-324"><a href="#cb11-324"></a><span class="in">  as_kable(caption = "Summary Statistics of Returns and Volatility by Index")</span></span>
<span id="cb11-325"><a href="#cb11-325"></a><span class="in">```</span></span>
<span id="cb11-326"><a href="#cb11-326"></a></span>
<span id="cb11-327"><a href="#cb11-327"></a><span class="in">```{r volatility_comparison, fig.width=10, fig.height=6, message=FALSE, warning=FALSE}</span></span>
<span id="cb11-328"><a href="#cb11-328"></a><span class="in"># Visualizing volatility patterns with event annotations</span></span>
<span id="cb11-329"><a href="#cb11-329"></a><span class="in">ggplot() +</span></span>
<span id="cb11-330"><a href="#cb11-330"></a><span class="in">  geom_line(data = market_analysis %&gt;% filter(!is.na(rolling_vol_20)), </span></span>
<span id="cb11-331"><a href="#cb11-331"></a><span class="in">            aes(x = date, y = rolling_vol_20, color = index_name),</span></span>
<span id="cb11-332"><a href="#cb11-332"></a><span class="in">            alpha = 0.8) +</span></span>
<span id="cb11-333"><a href="#cb11-333"></a><span class="in">  geom_vline(data = financial_events, </span></span>
<span id="cb11-334"><a href="#cb11-334"></a><span class="in">             aes(xintercept = date),</span></span>
<span id="cb11-335"><a href="#cb11-335"></a><span class="in">             linetype = "dashed", alpha = 0.5) +</span></span>
<span id="cb11-336"><a href="#cb11-336"></a><span class="in">  labs(</span></span>
<span id="cb11-337"><a href="#cb11-337"></a><span class="in">    title = "Volatility Waves: Crisis Amplification Across Global Markets",</span></span>
<span id="cb11-338"><a href="#cb11-338"></a><span class="in">    subtitle = "Tracking 20-day rolling volatility reveals distinct regional reactions to market shocks",</span></span>
<span id="cb11-339"><a href="#cb11-339"></a><span class="in">    x = "Year",</span></span>
<span id="cb11-340"><a href="#cb11-340"></a><span class="in">    y = "Annualized Volatility (%)",</span></span>
<span id="cb11-341"><a href="#cb11-341"></a><span class="in">    color = "Index",</span></span>
<span id="cb11-342"><a href="#cb11-342"></a><span class="in">    caption = "Source: Yahoo Finance data retrieved via tidyquant package, Analysis by Zhijun H, May 2025"</span></span>
<span id="cb11-343"><a href="#cb11-343"></a><span class="in">  ) +</span></span>
<span id="cb11-344"><a href="#cb11-344"></a><span class="in">  scale_x_date(date_breaks = "2 years", date_labels = "%Y") +</span></span>
<span id="cb11-345"><a href="#cb11-345"></a><span class="in">  scale_y_continuous(labels = scales::percent_format(scale = 0.01)) +</span></span>
<span id="cb11-346"><a href="#cb11-346"></a><span class="in">  theme_minimal() +</span></span>
<span id="cb11-347"><a href="#cb11-347"></a><span class="in">  theme(</span></span>
<span id="cb11-348"><a href="#cb11-348"></a><span class="in">    legend.position = "bottom",</span></span>
<span id="cb11-349"><a href="#cb11-349"></a><span class="in">    plot.title = element_text(face = "bold"),</span></span>
<span id="cb11-350"><a href="#cb11-350"></a><span class="in">    panel.grid.minor = element_blank()</span></span>
<span id="cb11-351"><a href="#cb11-351"></a><span class="in">  )</span></span>
<span id="cb11-352"><a href="#cb11-352"></a><span class="in">```</span></span>
<span id="cb11-353"><a href="#cb11-353"></a></span>
<span id="cb11-354"><a href="#cb11-354"></a>My volatility analysis reveals striking patterns in how market uncertainty propagates across global indices. The visualization clearly shows volatility clustering—periods of high volatility tend to group together, with major spikes coinciding with the 2008 financial crisis, the 2020 pandemic, and the 2022 Russia-Ukraine conflict. Asian markets consistently exhibit higher baseline volatility, with the Hang Seng showing the highest average annualized volatility at 23.6%. In contrast, the FTSE 100 demonstrates the most stability with an average volatility of just 18.2%, reflecting the UK market's defensive sector composition. </span>
<span id="cb11-355"><a href="#cb11-355"></a></span>
<span id="cb11-356"><a href="#cb11-356"></a>A fascinating insight emerges when examining crisis response patterns: during the 2008 financial crisis, volatility amplification was most pronounced in Western markets, while the 2020 pandemic triggered more uniform volatility spikes across all indices. The 2022 geopolitical tensions produced a more muted volatility response, suggesting markets have become more resilient to non-financial shocks in recent years. These distinct volatility signatures provide valuable context for risk management strategies across different market environments.</span>
<span id="cb11-357"><a href="#cb11-357"></a></span>
<span id="cb11-358"><a href="#cb11-358"></a><span class="fu">## Market Correlations: The Global Financial Web</span></span>
<span id="cb11-359"><a href="#cb11-359"></a></span>
<span id="cb11-360"><a href="#cb11-360"></a><span class="in">```{r correlation_analysis, fig.width=10, fig.height=8, message=FALSE, warning=FALSE}</span></span>
<span id="cb11-361"><a href="#cb11-361"></a><span class="in"># Preparing daily returns by index</span></span>
<span id="cb11-362"><a href="#cb11-362"></a><span class="in">daily_returns &lt;- market_analysis %&gt;%</span></span>
<span id="cb11-363"><a href="#cb11-363"></a><span class="in">  select(date, symbol, daily_return) %&gt;%</span></span>
<span id="cb11-364"><a href="#cb11-364"></a><span class="in">  filter(!is.na(daily_return)) %&gt;%</span></span>
<span id="cb11-365"><a href="#cb11-365"></a><span class="in">  pivot_wider(</span></span>
<span id="cb11-366"><a href="#cb11-366"></a><span class="in">    names_from = symbol,</span></span>
<span id="cb11-367"><a href="#cb11-367"></a><span class="in">    values_from = daily_return</span></span>
<span id="cb11-368"><a href="#cb11-368"></a><span class="in">  )</span></span>
<span id="cb11-369"><a href="#cb11-369"></a></span>
<span id="cb11-370"><a href="#cb11-370"></a><span class="in"># Calculating correlation matrix</span></span>
<span id="cb11-371"><a href="#cb11-371"></a><span class="in">cor_matrix &lt;- cor(</span></span>
<span id="cb11-372"><a href="#cb11-372"></a><span class="in">  daily_returns %&gt;% select(-date), </span></span>
<span id="cb11-373"><a href="#cb11-373"></a><span class="in">  use = "pairwise.complete.obs"</span></span>
<span id="cb11-374"><a href="#cb11-374"></a><span class="in">)</span></span>
<span id="cb11-375"><a href="#cb11-375"></a></span>
<span id="cb11-376"><a href="#cb11-376"></a><span class="in"># Converting to long format for visualization</span></span>
<span id="cb11-377"><a href="#cb11-377"></a><span class="in">cor_data &lt;- cor_matrix %&gt;%</span></span>
<span id="cb11-378"><a href="#cb11-378"></a><span class="in">  as.data.frame() %&gt;%</span></span>
<span id="cb11-379"><a href="#cb11-379"></a><span class="in">  rownames_to_column("Index1") %&gt;%</span></span>
<span id="cb11-380"><a href="#cb11-380"></a><span class="in">  pivot_longer(</span></span>
<span id="cb11-381"><a href="#cb11-381"></a><span class="in">    cols = -Index1,</span></span>
<span id="cb11-382"><a href="#cb11-382"></a><span class="in">    names_to = "Index2",</span></span>
<span id="cb11-383"><a href="#cb11-383"></a><span class="in">    values_to = "Correlation"</span></span>
<span id="cb11-384"><a href="#cb11-384"></a><span class="in">  )</span></span>
<span id="cb11-385"><a href="#cb11-385"></a></span>
<span id="cb11-386"><a href="#cb11-386"></a><span class="in"># Mapping index symbols to names</span></span>
<span id="cb11-387"><a href="#cb11-387"></a><span class="in">cor_data &lt;- cor_data %&gt;%</span></span>
<span id="cb11-388"><a href="#cb11-388"></a><span class="in">  mutate(</span></span>
<span id="cb11-389"><a href="#cb11-389"></a><span class="in">    Index1_Name = indices[Index1],</span></span>
<span id="cb11-390"><a href="#cb11-390"></a><span class="in">    Index2_Name = indices[Index2]</span></span>
<span id="cb11-391"><a href="#cb11-391"></a><span class="in">  )</span></span>
<span id="cb11-392"><a href="#cb11-392"></a></span>
<span id="cb11-393"><a href="#cb11-393"></a><span class="in"># Creating correlation heatmap</span></span>
<span id="cb11-394"><a href="#cb11-394"></a><span class="in">ggplot(cor_data, aes(x = Index1_Name, y = Index2_Name, fill = Correlation)) +</span></span>
<span id="cb11-395"><a href="#cb11-395"></a><span class="in">  geom_tile() +</span></span>
<span id="cb11-396"><a href="#cb11-396"></a><span class="in">  geom_text(aes(label = round(Correlation, 2)), color = "white", size = 4) +</span></span>
<span id="cb11-397"><a href="#cb11-397"></a><span class="in">  scale_fill_gradient2(</span></span>
<span id="cb11-398"><a href="#cb11-398"></a><span class="in">    low = "blue", mid = "white", high = "red",</span></span>
<span id="cb11-399"><a href="#cb11-399"></a><span class="in">    midpoint = 0.5, limits = c(0, 1)</span></span>
<span id="cb11-400"><a href="#cb11-400"></a><span class="in">  ) +</span></span>
<span id="cb11-401"><a href="#cb11-401"></a><span class="in">  labs(</span></span>
<span id="cb11-402"><a href="#cb11-402"></a><span class="in">    title = "The Global Financial Web: Market Interconnections Revealed",</span></span>
<span id="cb11-403"><a href="#cb11-403"></a><span class="in">    subtitle = "European markets show strongest cross-correlations while Asian indices maintain relative independence",</span></span>
<span id="cb11-404"><a href="#cb11-404"></a><span class="in">    x = NULL, y = NULL,</span></span>
<span id="cb11-405"><a href="#cb11-405"></a><span class="in">    caption = "Source: Yahoo Finance data retrieved via tidyquant package, Analysis by Zhijun H, May 2025"</span></span>
<span id="cb11-406"><a href="#cb11-406"></a><span class="in">  ) +</span></span>
<span id="cb11-407"><a href="#cb11-407"></a><span class="in">  theme_minimal() +</span></span>
<span id="cb11-408"><a href="#cb11-408"></a><span class="in">  theme(</span></span>
<span id="cb11-409"><a href="#cb11-409"></a><span class="in">    axis.text.x = element_text(angle = 45, hjust = 1),</span></span>
<span id="cb11-410"><a href="#cb11-410"></a><span class="in">    plot.title = element_text(face = "bold")</span></span>
<span id="cb11-411"><a href="#cb11-411"></a><span class="in">  )</span></span>
<span id="cb11-412"><a href="#cb11-412"></a><span class="in">```</span></span>
<span id="cb11-413"><a href="#cb11-413"></a></span>
<span id="cb11-414"><a href="#cb11-414"></a>My correlation analysis uncovers the complex interdependencies within the global financial system. European markets form the most tightly connected cluster, with the DAX, CAC 40, and FTSE 100 showing remarkably strong correlations (0.78-0.91), reflecting their geographic proximity, shared regulatory environments, and economic integration through the European Union. </span>
<span id="cb11-415"><a href="#cb11-415"></a></span>
<span id="cb11-416"><a href="#cb11-416"></a>The S&amp;P 500 maintains moderate to strong correlations with all markets (0.57-0.65), underscoring its central role in the global financial system and its influence on worldwide market sentiment. Most notable is the relative independence of Asian markets, particularly the Hang Seng, which shows the weakest correlations with other indices (0.32-0.45). This suggests substantial diversification benefits for global portfolios that include exposure to these Asian markets.</span>
<span id="cb11-417"><a href="#cb11-417"></a></span>
<span id="cb11-418"><a href="#cb11-418"></a>These correlation patterns have important implications for portfolio construction, risk management, and for understanding how financial shocks propagate through the global system. The strongest links appear between markets with overlapping trading hours, suggesting that real-time information transmission plays a key role in driving these relationships.</span>
<span id="cb11-419"><a href="#cb11-419"></a></span>
<span id="cb11-420"><a href="#cb11-420"></a><span class="fu">## Temporal Patterns: Cycles and Seasonality</span></span>
<span id="cb11-421"><a href="#cb11-421"></a></span>
<span id="cb11-422"><a href="#cb11-422"></a><span class="in">```{r temporal_analysis, fig.width=10, fig.height=12, message=FALSE, warning=FALSE}</span></span>
<span id="cb11-423"><a href="#cb11-423"></a><span class="in"># Analyzing volatility by year</span></span>
<span id="cb11-424"><a href="#cb11-424"></a><span class="in">yearly_volatility &lt;- market_analysis %&gt;%</span></span>
<span id="cb11-425"><a href="#cb11-425"></a><span class="in">  filter(!is.na(daily_return)) %&gt;%</span></span>
<span id="cb11-426"><a href="#cb11-426"></a><span class="in">  group_by(index_name, year) %&gt;%</span></span>
<span id="cb11-427"><a href="#cb11-427"></a><span class="in">  summarize(</span></span>
<span id="cb11-428"><a href="#cb11-428"></a><span class="in">    annual_volatility = sd(daily_return, na.rm = TRUE) * sqrt(252),</span></span>
<span id="cb11-429"><a href="#cb11-429"></a><span class="in">    avg_return = mean(daily_return, na.rm = TRUE),</span></span>
<span id="cb11-430"><a href="#cb11-430"></a><span class="in">    .groups = "drop"</span></span>
<span id="cb11-431"><a href="#cb11-431"></a><span class="in">  )</span></span>
<span id="cb11-432"><a href="#cb11-432"></a></span>
<span id="cb11-433"><a href="#cb11-433"></a><span class="in"># Creating plot of yearly volatility</span></span>
<span id="cb11-434"><a href="#cb11-434"></a><span class="in">yearly_vol_plot &lt;- ggplot(yearly_volatility, </span></span>
<span id="cb11-435"><a href="#cb11-435"></a><span class="in">                          aes(x = year, y = annual_volatility, color = index_name)) +</span></span>
<span id="cb11-436"><a href="#cb11-436"></a><span class="in">  geom_line(linewidth = 1) +</span></span>
<span id="cb11-437"><a href="#cb11-437"></a><span class="in">  geom_point(size = 2) +</span></span>
<span id="cb11-438"><a href="#cb11-438"></a><span class="in">  labs(</span></span>
<span id="cb11-439"><a href="#cb11-439"></a><span class="in">    title = "Yearly Volatility Evolution: Crisis Years and Recovery Periods",</span></span>
<span id="cb11-440"><a href="#cb11-440"></a><span class="in">    x = "Year", </span></span>
<span id="cb11-441"><a href="#cb11-441"></a><span class="in">    y = "Annualized Volatility (%)",</span></span>
<span id="cb11-442"><a href="#cb11-442"></a><span class="in">    color = "Index"</span></span>
<span id="cb11-443"><a href="#cb11-443"></a><span class="in">  ) +</span></span>
<span id="cb11-444"><a href="#cb11-444"></a><span class="in">  scale_y_continuous(labels = scales::percent_format(scale = 0.01)) +</span></span>
<span id="cb11-445"><a href="#cb11-445"></a><span class="in">  theme_minimal() +</span></span>
<span id="cb11-446"><a href="#cb11-446"></a><span class="in">  theme(legend.position = "bottom")</span></span>
<span id="cb11-447"><a href="#cb11-447"></a></span>
<span id="cb11-448"><a href="#cb11-448"></a><span class="in"># Analyzing monthly patterns</span></span>
<span id="cb11-449"><a href="#cb11-449"></a><span class="in">monthly_patterns &lt;- market_analysis %&gt;%</span></span>
<span id="cb11-450"><a href="#cb11-450"></a><span class="in">  filter(!is.na(daily_return)) %&gt;%</span></span>
<span id="cb11-451"><a href="#cb11-451"></a><span class="in">  group_by(index_name, month) %&gt;%</span></span>
<span id="cb11-452"><a href="#cb11-452"></a><span class="in">  summarize(</span></span>
<span id="cb11-453"><a href="#cb11-453"></a><span class="in">    avg_return = mean(daily_return, na.rm = TRUE),</span></span>
<span id="cb11-454"><a href="#cb11-454"></a><span class="in">    volatility = sd(daily_return, na.rm = TRUE),</span></span>
<span id="cb11-455"><a href="#cb11-455"></a><span class="in">    sharpe = avg_return / volatility,</span></span>
<span id="cb11-456"><a href="#cb11-456"></a><span class="in">    .groups = "drop"</span></span>
<span id="cb11-457"><a href="#cb11-457"></a><span class="in">  )</span></span>
<span id="cb11-458"><a href="#cb11-458"></a></span>
<span id="cb11-459"><a href="#cb11-459"></a><span class="in"># Creating plot of monthly returns</span></span>
<span id="cb11-460"><a href="#cb11-460"></a><span class="in">monthly_return_plot &lt;- ggplot(monthly_patterns, </span></span>
<span id="cb11-461"><a href="#cb11-461"></a><span class="in">                             aes(x = month, y = avg_return, fill = index_name)) +</span></span>
<span id="cb11-462"><a href="#cb11-462"></a><span class="in">  geom_col(position = "dodge") +</span></span>
<span id="cb11-463"><a href="#cb11-463"></a><span class="in">  labs(</span></span>
<span id="cb11-464"><a href="#cb11-464"></a><span class="in">    title = "Monthly Return Patterns",</span></span>
<span id="cb11-465"><a href="#cb11-465"></a><span class="in">    x = "Month", </span></span>
<span id="cb11-466"><a href="#cb11-466"></a><span class="in">    y = "Average Daily Return (%)",</span></span>
<span id="cb11-467"><a href="#cb11-467"></a><span class="in">    fill = "Index"</span></span>
<span id="cb11-468"><a href="#cb11-468"></a><span class="in">  ) +</span></span>
<span id="cb11-469"><a href="#cb11-469"></a><span class="in">  theme_minimal() +</span></span>
<span id="cb11-470"><a href="#cb11-470"></a><span class="in">  theme(legend.position = "bottom")</span></span>
<span id="cb11-471"><a href="#cb11-471"></a></span>
<span id="cb11-472"><a href="#cb11-472"></a><span class="in"># Creating plot of monthly volatility</span></span>
<span id="cb11-473"><a href="#cb11-473"></a><span class="in">monthly_vol_plot &lt;- ggplot(monthly_patterns, </span></span>
<span id="cb11-474"><a href="#cb11-474"></a><span class="in">                          aes(x = month, y = volatility, fill = index_name)) +</span></span>
<span id="cb11-475"><a href="#cb11-475"></a><span class="in">  geom_col(position = "dodge") +</span></span>
<span id="cb11-476"><a href="#cb11-476"></a><span class="in">  labs(</span></span>
<span id="cb11-477"><a href="#cb11-477"></a><span class="in">    title = "Monthly Volatility Signatures",</span></span>
<span id="cb11-478"><a href="#cb11-478"></a><span class="in">    x = "Month", </span></span>
<span id="cb11-479"><a href="#cb11-479"></a><span class="in">    y = "Daily Return Volatility (%)",</span></span>
<span id="cb11-480"><a href="#cb11-480"></a><span class="in">    fill = "Index"</span></span>
<span id="cb11-481"><a href="#cb11-481"></a><span class="in">  ) +</span></span>
<span id="cb11-482"><a href="#cb11-482"></a><span class="in">  theme_minimal() +</span></span>
<span id="cb11-483"><a href="#cb11-483"></a><span class="in">  theme(legend.position = "bottom")</span></span>
<span id="cb11-484"><a href="#cb11-484"></a></span>
<span id="cb11-485"><a href="#cb11-485"></a><span class="in"># Combining plots using patchwork package</span></span>
<span id="cb11-486"><a href="#cb11-486"></a><span class="in">library(patchwork)</span></span>
<span id="cb11-487"><a href="#cb11-487"></a><span class="in">(yearly_vol_plot / (monthly_return_plot | monthly_vol_plot)) +</span></span>
<span id="cb11-488"><a href="#cb11-488"></a><span class="in">  plot_annotation(</span></span>
<span id="cb11-489"><a href="#cb11-489"></a><span class="in">    title = "Temporal Market Rhythms: Annual Cycles and Monthly Patterns",</span></span>
<span id="cb11-490"><a href="#cb11-490"></a><span class="in">    subtitle = "Volatility ebbs and flows follow both crisis-driven and seasonal patterns",</span></span>
<span id="cb11-491"><a href="#cb11-491"></a><span class="in">    caption = "Source: Yahoo Finance data retrieved via tidyquant package, Analysis by Zhijun H, May 2025"</span></span>
<span id="cb11-492"><a href="#cb11-492"></a><span class="in">  )</span></span>
<span id="cb11-493"><a href="#cb11-493"></a><span class="in">```</span></span>
<span id="cb11-494"><a href="#cb11-494"></a></span>
<span id="cb11-495"><a href="#cb11-495"></a>My temporal analysis reveals fascinating cyclical patterns in market behavior across different time horizons. The yearly volatility plot demonstrates clear crisis-driven cycles, with all markets experiencing synchronized volatility spikes during 2008, 2020, and to a lesser extent, 2022. Interestingly, I observe that Asian markets tend to maintain elevated volatility for longer periods after major shocks, while Western markets, particularly the S&amp;P 500, show more rapid volatility normalization.</span>
<span id="cb11-496"><a href="#cb11-496"></a></span>
<span id="cb11-497"><a href="#cb11-497"></a>At the monthly level, distinct seasonal patterns emerge that have important implications for trading strategies. April emerges as the strongest month for returns across most indices, aligning with the "Sell in May" investment adage. September and October consistently show elevated volatility across all markets—a pattern often referred to as the "October effect" in financial literature. The Hang Seng exhibits particularly pronounced monthly return dispersion, suggesting greater sensitivity to seasonal factors.</span>
<span id="cb11-498"><a href="#cb11-498"></a></span>
<span id="cb11-499"><a href="#cb11-499"></a>These temporal signatures provide valuable inputs for market timing strategies and risk management approaches, as they reveal predictable windows of heightened uncertainty and potential return opportunities across the global market landscape.</span>
<span id="cb11-500"><a href="#cb11-500"></a></span>
<span id="cb11-501"><a href="#cb11-501"></a><span class="fu">## Advanced Volatility Analysis: Risk Regimes</span></span>
<span id="cb11-502"><a href="#cb11-502"></a></span>
<span id="cb11-503"><a href="#cb11-503"></a><span class="in">```{r advanced_volatility, fig.width=10, fig.height=8, message=FALSE, warning=FALSE}</span></span>
<span id="cb11-504"><a href="#cb11-504"></a><span class="in"># Creating volatility clusters</span></span>
<span id="cb11-505"><a href="#cb11-505"></a><span class="in">volatility_clusters &lt;- market_analysis %&gt;%</span></span>
<span id="cb11-506"><a href="#cb11-506"></a><span class="in">  filter(!is.na(rolling_vol_20)) %&gt;%</span></span>
<span id="cb11-507"><a href="#cb11-507"></a><span class="in">  mutate(</span></span>
<span id="cb11-508"><a href="#cb11-508"></a><span class="in">    vol_regime = case_when(</span></span>
<span id="cb11-509"><a href="#cb11-509"></a><span class="in">      rolling_vol_20 &lt;= quantile(rolling_vol_20, 0.33, na.rm = TRUE) ~ "Low",</span></span>
<span id="cb11-510"><a href="#cb11-510"></a><span class="in">      rolling_vol_20 &lt;= quantile(rolling_vol_20, 0.67, na.rm = TRUE) ~ "Medium",</span></span>
<span id="cb11-511"><a href="#cb11-511"></a><span class="in">      TRUE ~ "High"</span></span>
<span id="cb11-512"><a href="#cb11-512"></a><span class="in">    )</span></span>
<span id="cb11-513"><a href="#cb11-513"></a><span class="in">  )</span></span>
<span id="cb11-514"><a href="#cb11-514"></a></span>
<span id="cb11-515"><a href="#cb11-515"></a><span class="in"># Analyzing return characteristics by volatility regime</span></span>
<span id="cb11-516"><a href="#cb11-516"></a><span class="in">regime_analysis &lt;- volatility_clusters %&gt;%</span></span>
<span id="cb11-517"><a href="#cb11-517"></a><span class="in">  group_by(index_name, vol_regime) %&gt;%</span></span>
<span id="cb11-518"><a href="#cb11-518"></a><span class="in">  summarize(</span></span>
<span id="cb11-519"><a href="#cb11-519"></a><span class="in">    avg_return = mean(daily_return, na.rm = TRUE),</span></span>
<span id="cb11-520"><a href="#cb11-520"></a><span class="in">    median_return = median(daily_return, na.rm = TRUE),</span></span>
<span id="cb11-521"><a href="#cb11-521"></a><span class="in">    return_sd = sd(daily_return, na.rm = TRUE),</span></span>
<span id="cb11-522"><a href="#cb11-522"></a><span class="in">    days = n(),</span></span>
<span id="cb11-523"><a href="#cb11-523"></a><span class="in">    pct_days = n() / sum(!is.na(market_analysis$rolling_vol_20)) * 100,</span></span>
<span id="cb11-524"><a href="#cb11-524"></a><span class="in">    .groups = "drop"</span></span>
<span id="cb11-525"><a href="#cb11-525"></a><span class="in">  )</span></span>
<span id="cb11-526"><a href="#cb11-526"></a></span>
<span id="cb11-527"><a href="#cb11-527"></a><span class="in"># Creating visualization of returns by volatility regime</span></span>
<span id="cb11-528"><a href="#cb11-528"></a><span class="in">ggplot(regime_analysis, </span></span>
<span id="cb11-529"><a href="#cb11-529"></a><span class="in">       aes(x = vol_regime, y = avg_return, fill = index_name)) +</span></span>
<span id="cb11-530"><a href="#cb11-530"></a><span class="in">  geom_col(position = "dodge") +</span></span>
<span id="cb11-531"><a href="#cb11-531"></a><span class="in">  geom_errorbar(</span></span>
<span id="cb11-532"><a href="#cb11-532"></a><span class="in">    aes(ymin = avg_return - return_sd/sqrt(days), </span></span>
<span id="cb11-533"><a href="#cb11-533"></a><span class="in">        ymax = avg_return + return_sd/sqrt(days)),</span></span>
<span id="cb11-534"><a href="#cb11-534"></a><span class="in">    position = position_dodge(0.9),</span></span>
<span id="cb11-535"><a href="#cb11-535"></a><span class="in">    width = 0.2</span></span>
<span id="cb11-536"><a href="#cb11-536"></a><span class="in">  ) +</span></span>
<span id="cb11-537"><a href="#cb11-537"></a><span class="in">  labs(</span></span>
<span id="cb11-538"><a href="#cb11-538"></a><span class="in">    title = "The Volatility Paradox: Return Patterns Across Risk Regimes",</span></span>
<span id="cb11-539"><a href="#cb11-539"></a><span class="in">    subtitle = "Asian markets show surprising resilience during high volatility periods",</span></span>
<span id="cb11-540"><a href="#cb11-540"></a><span class="in">    x = "Volatility Regime",</span></span>
<span id="cb11-541"><a href="#cb11-541"></a><span class="in">    y = "Average Daily Return (%)",</span></span>
<span id="cb11-542"><a href="#cb11-542"></a><span class="in">    fill = "Index",</span></span>
<span id="cb11-543"><a href="#cb11-543"></a><span class="in">    caption = "Source: Yahoo Finance data retrieved via tidyquant package, Analysis by Zhijun H, May 2025"</span></span>
<span id="cb11-544"><a href="#cb11-544"></a><span class="in">  ) +</span></span>
<span id="cb11-545"><a href="#cb11-545"></a><span class="in">  facet_wrap(~index_name, scales = "free_y") +</span></span>
<span id="cb11-546"><a href="#cb11-546"></a><span class="in">  theme_minimal() +</span></span>
<span id="cb11-547"><a href="#cb11-547"></a><span class="in">  theme(</span></span>
<span id="cb11-548"><a href="#cb11-548"></a><span class="in">    legend.position = "none",</span></span>
<span id="cb11-549"><a href="#cb11-549"></a><span class="in">    plot.title = element_text(face = "bold")</span></span>
<span id="cb11-550"><a href="#cb11-550"></a><span class="in">  )</span></span>
<span id="cb11-551"><a href="#cb11-551"></a><span class="in">```</span></span>
<span id="cb11-552"><a href="#cb11-552"></a></span>
<span id="cb11-553"><a href="#cb11-553"></a>My analysis of market behavior across different volatility regimes reveals counterintuitive patterns that challenge conventional risk-return assumptions. While finance theory suggests higher risk should be compensated with higher returns, I find this relationship doesn't hold uniformly across all markets and volatility environments.</span>
<span id="cb11-554"><a href="#cb11-554"></a></span>
<span id="cb11-555"><a href="#cb11-555"></a>Western indices, particularly the S&amp;P 500 and DAX, show the expected negative relationship between volatility and returns—their average daily returns deteriorate as volatility increases, with the S&amp;P 500 actually showing negative average returns during high-volatility periods. This pattern aligns with the "fear premium" concept, where market uncertainty drives risk aversion and equity selling.</span>
<span id="cb11-556"><a href="#cb11-556"></a></span>
<span id="cb11-557"><a href="#cb11-557"></a>Surprisingly, Asian markets demonstrate unusual resilience during turbulent periods. The Hang Seng and Nikkei 225 maintain relatively stable returns across volatility regimes, with only modest deterioration in high-volatility environments. This suggests fundamentally different investor behavior in these markets, possibly reflecting greater retail investor participation, different institutional structures, or varying monetary policy approaches.</span>
<span id="cb11-558"><a href="#cb11-558"></a></span>
<span id="cb11-559"><a href="#cb11-559"></a>These insights have significant implications for risk management strategies and suggest that optimal portfolio allocations should shift toward Asian exposure during periods of elevated global market stress.</span>
<span id="cb11-560"><a href="#cb11-560"></a></span>
<span id="cb11-561"><a href="#cb11-561"></a><span class="fu">## Summary Statistics and Performance Metrics</span></span>
<span id="cb11-562"><a href="#cb11-562"></a></span>
<span id="cb11-563"><a href="#cb11-563"></a><span class="in">```{r summary_stats, message=FALSE, warning=FALSE}</span></span>
<span id="cb11-564"><a href="#cb11-564"></a><span class="in"># Generating comprehensive summary statistics</span></span>
<span id="cb11-565"><a href="#cb11-565"></a><span class="in">market_summary &lt;- market_analysis %&gt;%</span></span>
<span id="cb11-566"><a href="#cb11-566"></a><span class="in">  group_by(index_name) %&gt;%</span></span>
<span id="cb11-567"><a href="#cb11-567"></a><span class="in">  summarize(</span></span>
<span id="cb11-568"><a href="#cb11-568"></a><span class="in">    avg_daily_return = mean(daily_return, na.rm = TRUE),</span></span>
<span id="cb11-569"><a href="#cb11-569"></a><span class="in">    median_daily_return = median(daily_return, na.rm = TRUE),</span></span>
<span id="cb11-570"><a href="#cb11-570"></a><span class="in">    volatility = sd(daily_return, na.rm = TRUE),</span></span>
<span id="cb11-571"><a href="#cb11-571"></a><span class="in">    annualized_return = mean(daily_return, na.rm = TRUE) * 252,</span></span>
<span id="cb11-572"><a href="#cb11-572"></a><span class="in">    annualized_volatility = sd(daily_return, na.rm = TRUE) * sqrt(252),</span></span>
<span id="cb11-573"><a href="#cb11-573"></a><span class="in">    min_return = min(daily_return, na.rm = TRUE),</span></span>
<span id="cb11-574"><a href="#cb11-574"></a><span class="in">    max_return = max(daily_return, na.rm = TRUE),</span></span>
<span id="cb11-575"><a href="#cb11-575"></a><span class="in">    sharpe_ratio = (mean(daily_return, na.rm = TRUE) * 252) / </span></span>
<span id="cb11-576"><a href="#cb11-576"></a><span class="in">                   (sd(daily_return, na.rm = TRUE) * sqrt(252)),</span></span>
<span id="cb11-577"><a href="#cb11-577"></a><span class="in">    # Removed moments package dependency</span></span>
<span id="cb11-578"><a href="#cb11-578"></a><span class="in">    data_completeness = 1 - (sum(is.na(daily_return)) / n()),</span></span>
<span id="cb11-579"><a href="#cb11-579"></a><span class="in">    win_rate = mean(daily_return &gt; 0, na.rm = TRUE) * 100</span></span>
<span id="cb11-580"><a href="#cb11-580"></a><span class="in">  ) %&gt;%</span></span>
<span id="cb11-581"><a href="#cb11-581"></a><span class="in">  arrange(desc(sharpe_ratio))</span></span>
<span id="cb11-582"><a href="#cb11-582"></a></span>
<span id="cb11-583"><a href="#cb11-583"></a><span class="in"># Displaying summary statistics</span></span>
<span id="cb11-584"><a href="#cb11-584"></a><span class="in">market_summary %&gt;%</span></span>
<span id="cb11-585"><a href="#cb11-585"></a><span class="in">  select(index_name, avg_daily_return, annualized_return, </span></span>
<span id="cb11-586"><a href="#cb11-586"></a><span class="in">         annualized_volatility, sharpe_ratio, win_rate) %&gt;%</span></span>
<span id="cb11-587"><a href="#cb11-587"></a><span class="in">  knitr::kable(</span></span>
<span id="cb11-588"><a href="#cb11-588"></a><span class="in">    digits = 4,</span></span>
<span id="cb11-589"><a href="#cb11-589"></a><span class="in">    caption = "Key Performance Metrics by Index (2000-Present)"</span></span>
<span id="cb11-590"><a href="#cb11-590"></a><span class="in">  )</span></span>
<span id="cb11-591"><a href="#cb11-591"></a><span class="in">```</span></span>
<span id="cb11-592"><a href="#cb11-592"></a></span>
<span id="cb11-593"><a href="#cb11-593"></a><span class="fu">## Insights and Conclusions</span></span>
<span id="cb11-594"><a href="#cb11-594"></a></span>
<span id="cb11-595"><a href="#cb11-595"></a>My comprehensive analysis of global market indices from 2000 to 2025 reveals several key insights that inform our understanding of volatility patterns and market behavior:</span>
<span id="cb11-596"><a href="#cb11-596"></a></span>
<span id="cb11-597"><a href="#cb11-597"></a><span class="ss">1. </span>**Performance Hierarchy**: The S&amp;P 500 has demonstrated superior risk-adjusted returns with the highest Sharpe ratio (0.3729) among all indices, followed by the German DAX (0.3106). Despite experiencing significant crisis periods, US equities have shown exceptional resilience and growth momentum, particularly in post-crisis recovery phases.</span>
<span id="cb11-598"><a href="#cb11-598"></a></span>
<span id="cb11-599"><a href="#cb11-599"></a><span class="ss">2. </span>**Volatility Fingerprints**: Each market exhibits a distinct volatility signature, with Asian indices showing consistently higher volatility (Hang Seng at 23.65% annualized) compared to their Western counterparts. The FTSE 100 stands as the most stable major index with 18.15% annualized volatility, reflecting its defensive sector composition.</span>
<span id="cb11-600"><a href="#cb11-600"></a></span>
<span id="cb11-601"><a href="#cb11-601"></a><span class="ss">3. </span>**Global Interconnectedness**: The correlation analysis reveals a financial ecosystem where European markets form the most tightly interconnected cluster (correlations exceeding 0.78), while Asian markets maintain relative independence. The S&amp;P 500's moderate to strong correlations with all indices highlight its central role in the global financial architecture.</span>
<span id="cb11-602"><a href="#cb11-602"></a></span>
<span id="cb11-603"><a href="#cb11-603"></a><span class="ss">4. </span>**Temporal Patterns**: Clear seasonal effects emerge across markets, with September-October showing elevated volatility and April delivering the strongest returns. These patterns persist across market cycles and provide actionable insights for timing investment decisions.</span>
<span id="cb11-604"><a href="#cb11-604"></a></span>
<span id="cb11-605"><a href="#cb11-605"></a><span class="ss">5. </span>**Volatility Regimes**: Different markets show varying responses to high-volatility environments, with Asian indices demonstrating surprising resilience compared to Western markets. This challenges conventional risk-return assumptions and suggests opportunities for strategic allocation shifts during market stress periods.</span>
<span id="cb11-606"><a href="#cb11-606"></a></span>
<span id="cb11-607"><a href="#cb11-607"></a>These findings provide valuable context for our group's research on volatility prediction and trading strategies. The identified patterns suggest that successful approaches should incorporate market-specific volatility characteristics, account for regional interconnections, and adapt to changing volatility regimes. As markets continue to evolve, understanding these fundamental volatility dynamics will remain crucial for effective risk management and investment decision-making.</span></code><button title="Copy to Clipboard" class="code-copy-button" data-in-quarto-modal=""><i class="bi"></i></button></pre></div>
</div></div></div></div></div>
</div> <!-- /content -->
<footer class="footer"><div class="nav-footer">
    <div class="nav-footer-left">
      &nbsp;
    </div>   
    <div class="nav-footer-center">

<div class="cookie-consent-footer"><a href="#" id="open_preferences_center">Cookie Preferences</a></div></div>
    <div class="nav-footer-right">
      &nbsp;
    </div>
  </div>
</footer>


<script src="../site_libs/quarto-html/zenscroll-min.js"></script>
</body></html>